/*
Package exampleoc is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was true
in this case).

This package was generated by /usr/local/google/home/dgrau/go/pkg/mod/github.com/openconfig/ygot@v0.18.0/genutil/names.go
using the following YANG input files:
	- ../../pathgen/testdata/yang/openconfig-simple.yang
	- ../../pathgen/testdata/yang/openconfig-withlist.yang
Imported modules were sourced from:
	- ../../pathgen/testdata/yang/...
*/
package exampleoc

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/ygot/ytypes"
)

// Binary is a type that is used for fields that have a YANG type of
// binary. It is used such that binary fields can be distinguished from
// leaf-lists of uint8s (which are mapped to []uint8, equivalent to
// []byte in reflection).
type Binary []byte

// YANGEmpty is a type that is used for fields that have a YANG type of
// empty. It is used such that empty fields can be distinguished from boolean fields
// in the generated code.
type YANGEmpty bool

// UnionInt8 is an int8 type assignable to unions of which it is a subtype.
type UnionInt8 int8

// UnionInt16 is an int16 type assignable to unions of which it is a subtype.
type UnionInt16 int16

// UnionInt32 is an int32 type assignable to unions of which it is a subtype.
type UnionInt32 int32

// UnionInt64 is an int64 type assignable to unions of which it is a subtype.
type UnionInt64 int64

// UnionUint8 is a uint8 type assignable to unions of which it is a subtype.
type UnionUint8 uint8

// UnionUint16 is a uint16 type assignable to unions of which it is a subtype.
type UnionUint16 uint16

// UnionUint32 is a uint32 type assignable to unions of which it is a subtype.
type UnionUint32 uint32

// UnionUint64 is a uint64 type assignable to unions of which it is a subtype.
type UnionUint64 uint64

// UnionFloat64 is a float64 type assignable to unions of which it is a subtype.
type UnionFloat64 float64

// UnionString is a string type assignable to unions of which it is a subtype.
type UnionString string

// UnionBool is a bool type assignable to unions of which it is a subtype.
type UnionBool bool

// UnionUnsupported is an interface{} wrapper type for unsupported types. It is
// assignable to unions of which it is a subtype.
type UnionUnsupported struct {
	Value interface{}
}

var (
	SchemaTree map[string]*yang.Entry
)

func init() {
	var err error
	if SchemaTree, err = UnzipSchema(); err != nil {
		panic("schema error: " + err.Error())
	}
}

// Schema returns the details of the generated schema.
func Schema() (*ytypes.Schema, error) {
	uzp, err := UnzipSchema()
	if err != nil {
		return nil, fmt.Errorf("cannot unzip schema, %v", err)
	}

	return &ytypes.Schema{
		Root:       &Device{},
		SchemaTree: uzp,
		Unmarshal:  Unmarshal,
	}, nil
}

// UnzipSchema unzips the zipped schema and returns a map of yang.Entry nodes,
// keyed by the name of the struct that the yang.Entry describes the schema for.
func UnzipSchema() (map[string]*yang.Entry, error) {
	var schemaTree map[string]*yang.Entry
	var err error
	if schemaTree, err = ygot.GzipToSchema(ySchema); err != nil {
		return nil, fmt.Errorf("could not unzip the schema; %v", err)
	}
	return schemaTree, nil
}

// Unmarshal unmarshals data, which must be RFC7951 JSON format, into
// destStruct, which must be non-nil and the correct GoStruct type. It returns
// an error if the destStruct is not found in the schema or the data cannot be
// unmarshaled. The supplied options (opts) are used to control the behaviour
// of the unmarshal function - for example, determining whether errors are
// thrown for unknown fields in the input JSON.
func Unmarshal(data []byte, destStruct ygot.ValidatedGoStruct, opts ...ytypes.UnmarshalOpt) error {
	tn := reflect.TypeOf(destStruct).Elem().Name()
	schema, ok := SchemaTree[tn]
	if !ok {
		return fmt.Errorf("could not find schema for type %s", tn)
	}
	var jsonTree interface{}
	if err := json.Unmarshal([]byte(data), &jsonTree); err != nil {
		return err
	}
	return ytypes.Unmarshal(schema, destStruct, jsonTree, opts...)
}

// Device represents the /device YANG schema element.
type Device struct {
	Model           *Model           `path:"model" module:"openconfig-withlist"`
	Parent          *Parent          `path:"parent" module:"openconfig-simple"`
	RemoteContainer *RemoteContainer `path:"remote-container" module:"openconfig-simple"`
}

// IsYANGGoStruct ensures that Device implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Device) IsYANGGoStruct() {}

// GetOrCreateModel retrieves the value of the Model field
// or returns the existing field if it already exists.
func (t *Device) GetOrCreateModel() *Model {
	if t.Model != nil {
		return t.Model
	}
	t.Model = &Model{}
	return t.Model
}

// GetOrCreateParent retrieves the value of the Parent field
// or returns the existing field if it already exists.
func (t *Device) GetOrCreateParent() *Parent {
	if t.Parent != nil {
		return t.Parent
	}
	t.Parent = &Parent{}
	return t.Parent
}

// GetOrCreateRemoteContainer retrieves the value of the RemoteContainer field
// or returns the existing field if it already exists.
func (t *Device) GetOrCreateRemoteContainer() *RemoteContainer {
	if t.RemoteContainer != nil {
		return t.RemoteContainer
	}
	t.RemoteContainer = &RemoteContainer{}
	return t.RemoteContainer
}

// GetModel returns the value of the Model struct pointer
// from Device. If the receiver or the field Model is nil, nil
// is returned such that the Get* methods can be safely chained.
func (t *Device) GetModel() *Model {
	if t != nil && t.Model != nil {
		return t.Model
	}
	return nil
}

// GetParent returns the value of the Parent struct pointer
// from Device. If the receiver or the field Parent is nil, nil
// is returned such that the Get* methods can be safely chained.
func (t *Device) GetParent() *Parent {
	if t != nil && t.Parent != nil {
		return t.Parent
	}
	return nil
}

// GetRemoteContainer returns the value of the RemoteContainer struct pointer
// from Device. If the receiver or the field RemoteContainer is nil, nil
// is returned such that the Get* methods can be safely chained.
func (t *Device) GetRemoteContainer() *RemoteContainer {
	if t != nil && t.RemoteContainer != nil {
		return t.RemoteContainer
	}
	return nil
}

// PopulateDefaults recursively populates unset leaf fields in the Device
// with default values as specified in the YANG schema, instantiating any nil
// container fields.
func (t *Device) PopulateDefaults() {
	if t == nil {
		return
	}
	ygot.BuildEmptyTree(t)
	t.Model.PopulateDefaults()
	t.Parent.PopulateDefaults()
	t.RemoteContainer.PopulateDefaults()
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Device) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Device"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Device) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module in whose namespace
// Device belongs.
func (*Device) ΛBelongingModule() string {
	return ""
}

// Model represents the /openconfig-withlist/model YANG schema element.
type Model struct {
	MultiKey  map[Model_MultiKey_Key]*Model_MultiKey `path:"b/multi-key" module:"openconfig-withlist/openconfig-withlist"`
	SingleKey map[string]*Model_SingleKey            `path:"a/single-key" module:"openconfig-withlist/openconfig-withlist"`
}

// IsYANGGoStruct ensures that Model implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Model) IsYANGGoStruct() {}

// Model_MultiKey_Key represents the key for list MultiKey of element /openconfig-withlist/model.
type Model_MultiKey_Key struct {
	Key1 uint32 `path:"key1"`
	Key2 uint64 `path:"key2"`
}

// NewMultiKey creates a new entry in the MultiKey list of the
// Model struct. The keys of the list are populated from the input
// arguments.
func (t *Model) NewMultiKey(Key1 uint32, Key2 uint64) (*Model_MultiKey, error) {

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.MultiKey == nil {
		t.MultiKey = make(map[Model_MultiKey_Key]*Model_MultiKey)
	}

	key := Model_MultiKey_Key{
		Key1: Key1,
		Key2: Key2,
	}

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.MultiKey[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list MultiKey", key)
	}

	t.MultiKey[key] = &Model_MultiKey{
		Key1: &Key1,
		Key2: &Key2,
	}

	return t.MultiKey[key], nil
}

// RenameMultiKey renames an entry in the list MultiKey within
// the Model struct. The entry with key oldK is renamed to newK updating
// the key within the value.
func (t *Model) RenameMultiKey(oldK, newK Model_MultiKey_Key) error {
	if _, ok := t.MultiKey[newK]; ok {
		return fmt.Errorf("key %v already exists in MultiKey", newK)
	}

	e, ok := t.MultiKey[oldK]
	if !ok {
		return fmt.Errorf("key %v not found in MultiKey", oldK)
	}
	e.Key1 = &newK.Key1
	e.Key2 = &newK.Key2

	t.MultiKey[newK] = e
	delete(t.MultiKey, oldK)
	return nil
}

// GetOrCreateMultiKey retrieves the value with the specified keys from
// the receiver Model. If the entry does not exist, then it is created.
// It returns the existing or new list member.
func (t *Model) GetOrCreateMultiKey(Key1 uint32, Key2 uint64) *Model_MultiKey {

	key := Model_MultiKey_Key{
		Key1: Key1,
		Key2: Key2,
	}

	if v, ok := t.MultiKey[key]; ok {
		return v
	}
	// Panic if we receive an error, since we should have retrieved an existing
	// list member. This allows chaining of GetOrCreate methods.
	v, err := t.NewMultiKey(Key1, Key2)
	if err != nil {
		panic(fmt.Sprintf("GetOrCreateMultiKey got unexpected error: %v", err))
	}
	return v
}

// GetMultiKey retrieves the value with the specified key from
// the MultiKey map field of Model. If the receiver is nil, or
// the specified key is not present in the list, nil is returned such that Get*
// methods may be safely chained.
func (t *Model) GetMultiKey(Key1 uint32, Key2 uint64) *Model_MultiKey {

	if t == nil {
		return nil
	}

	key := Model_MultiKey_Key{
		Key1: Key1,
		Key2: Key2,
	}

	if lm, ok := t.MultiKey[key]; ok {
		return lm
	}
	return nil
}

// DeleteMultiKey deletes the value with the specified keys from
// the receiver Model. If there is no such element, the function
// is a no-op.
func (t *Model) DeleteMultiKey(Key1 uint32, Key2 uint64) {
	key := Model_MultiKey_Key{
		Key1: Key1,
		Key2: Key2,
	}

	delete(t.MultiKey, key)
}

// AppendMultiKey appends the supplied Model_MultiKey struct to the
// list MultiKey of Model. If the key value(s) specified in
// the supplied Model_MultiKey already exist in the list, an error is
// returned.
func (t *Model) AppendMultiKey(v *Model_MultiKey) error {
	if v.Key1 == nil {
		return fmt.Errorf("invalid nil key for Key1")
	}

	if v.Key2 == nil {
		return fmt.Errorf("invalid nil key for Key2")
	}

	key := Model_MultiKey_Key{
		Key1: *v.Key1,
		Key2: *v.Key2,
	}

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.MultiKey == nil {
		t.MultiKey = make(map[Model_MultiKey_Key]*Model_MultiKey)
	}

	if _, ok := t.MultiKey[key]; ok {
		return fmt.Errorf("duplicate key for list MultiKey %v", key)
	}

	t.MultiKey[key] = v
	return nil
}

// NewSingleKey creates a new entry in the SingleKey list of the
// Model struct. The keys of the list are populated from the input
// arguments.
func (t *Model) NewSingleKey(Key string) (*Model_SingleKey, error) {

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.SingleKey == nil {
		t.SingleKey = make(map[string]*Model_SingleKey)
	}

	key := Key

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.SingleKey[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list SingleKey", key)
	}

	t.SingleKey[key] = &Model_SingleKey{
		Key: &Key,
	}

	return t.SingleKey[key], nil
}

// RenameSingleKey renames an entry in the list SingleKey within
// the Model struct. The entry with key oldK is renamed to newK updating
// the key within the value.
func (t *Model) RenameSingleKey(oldK, newK string) error {
	if _, ok := t.SingleKey[newK]; ok {
		return fmt.Errorf("key %v already exists in SingleKey", newK)
	}

	e, ok := t.SingleKey[oldK]
	if !ok {
		return fmt.Errorf("key %v not found in SingleKey", oldK)
	}
	e.Key = &newK

	t.SingleKey[newK] = e
	delete(t.SingleKey, oldK)
	return nil
}

// GetOrCreateSingleKey retrieves the value with the specified keys from
// the receiver Model. If the entry does not exist, then it is created.
// It returns the existing or new list member.
func (t *Model) GetOrCreateSingleKey(Key string) *Model_SingleKey {

	key := Key

	if v, ok := t.SingleKey[key]; ok {
		return v
	}
	// Panic if we receive an error, since we should have retrieved an existing
	// list member. This allows chaining of GetOrCreate methods.
	v, err := t.NewSingleKey(Key)
	if err != nil {
		panic(fmt.Sprintf("GetOrCreateSingleKey got unexpected error: %v", err))
	}
	return v
}

// GetSingleKey retrieves the value with the specified key from
// the SingleKey map field of Model. If the receiver is nil, or
// the specified key is not present in the list, nil is returned such that Get*
// methods may be safely chained.
func (t *Model) GetSingleKey(Key string) *Model_SingleKey {

	if t == nil {
		return nil
	}

	key := Key

	if lm, ok := t.SingleKey[key]; ok {
		return lm
	}
	return nil
}

// DeleteSingleKey deletes the value with the specified keys from
// the receiver Model. If there is no such element, the function
// is a no-op.
func (t *Model) DeleteSingleKey(Key string) {
	key := Key

	delete(t.SingleKey, key)
}

// AppendSingleKey appends the supplied Model_SingleKey struct to the
// list SingleKey of Model. If the key value(s) specified in
// the supplied Model_SingleKey already exist in the list, an error is
// returned.
func (t *Model) AppendSingleKey(v *Model_SingleKey) error {
	if v.Key == nil {
		return fmt.Errorf("invalid nil key received for Key")
	}

	key := *v.Key

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.SingleKey == nil {
		t.SingleKey = make(map[string]*Model_SingleKey)
	}

	if _, ok := t.SingleKey[key]; ok {
		return fmt.Errorf("duplicate key for list SingleKey %v", key)
	}

	t.SingleKey[key] = v
	return nil
}

// PopulateDefaults recursively populates unset leaf fields in the Model
// with default values as specified in the YANG schema, instantiating any nil
// container fields.
func (t *Model) PopulateDefaults() {
	if t == nil {
		return
	}
	ygot.BuildEmptyTree(t)
	for _, e := range t.MultiKey {
		e.PopulateDefaults()
	}
	for _, e := range t.SingleKey {
		e.PopulateDefaults()
	}
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Model) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Model"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Model) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module in whose namespace
// Model belongs.
func (*Model) ΛBelongingModule() string {
	return "openconfig-withlist"
}

// Model_MultiKey represents the /openconfig-withlist/model/b/multi-key YANG schema element.
type Model_MultiKey struct {
	Key1 *uint32 `path:"state/key1|key1" module:"openconfig-withlist/openconfig-withlist|openconfig-withlist" shadow-path:"config/key1|key1" shadow-module:"openconfig-withlist/openconfig-withlist|openconfig-withlist"`
	Key2 *uint64 `path:"state/key2|key2" module:"openconfig-withlist/openconfig-withlist|openconfig-withlist" shadow-path:"config/key2|key2" shadow-module:"openconfig-withlist/openconfig-withlist|openconfig-withlist"`
}

// IsYANGGoStruct ensures that Model_MultiKey implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Model_MultiKey) IsYANGGoStruct() {}

// GetKey1 retrieves the value of the leaf Key1 from the Model_MultiKey
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Key1 is set, it can
// safely use t.GetKey1() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Key1 == nil' before retrieving the leaf's value.
func (t *Model_MultiKey) GetKey1() uint32 {
	if t == nil || t.Key1 == nil {
		return 0
	}
	return *t.Key1
}

// GetKey2 retrieves the value of the leaf Key2 from the Model_MultiKey
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Key2 is set, it can
// safely use t.GetKey2() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Key2 == nil' before retrieving the leaf's value.
func (t *Model_MultiKey) GetKey2() uint64 {
	if t == nil || t.Key2 == nil {
		return 0
	}
	return *t.Key2
}

// PopulateDefaults recursively populates unset leaf fields in the Model_MultiKey
// with default values as specified in the YANG schema, instantiating any nil
// container fields.
func (t *Model_MultiKey) PopulateDefaults() {
	if t == nil {
		return
	}
	ygot.BuildEmptyTree(t)
}

// ΛListKeyMap returns the keys of the Model_MultiKey struct, which is a YANG list entry.
func (t *Model_MultiKey) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Key1 == nil {
		return nil, fmt.Errorf("nil value for key Key1")
	}

	if t.Key2 == nil {
		return nil, fmt.Errorf("nil value for key Key2")
	}

	return map[string]interface{}{
		"key1": *t.Key1,
		"key2": *t.Key2,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Model_MultiKey) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Model_MultiKey"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Model_MultiKey) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module in whose namespace
// Model_MultiKey belongs.
func (*Model_MultiKey) ΛBelongingModule() string {
	return "openconfig-withlist"
}

// Model_SingleKey represents the /openconfig-withlist/model/a/single-key YANG schema element.
type Model_SingleKey struct {
	Key *string `path:"state/key|key" module:"openconfig-withlist/openconfig-withlist|openconfig-withlist" shadow-path:"config/key|key" shadow-module:"openconfig-withlist/openconfig-withlist|openconfig-withlist"`
}

// IsYANGGoStruct ensures that Model_SingleKey implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Model_SingleKey) IsYANGGoStruct() {}

// GetKey retrieves the value of the leaf Key from the Model_SingleKey
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Key is set, it can
// safely use t.GetKey() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Key == nil' before retrieving the leaf's value.
func (t *Model_SingleKey) GetKey() string {
	if t == nil || t.Key == nil {
		return ""
	}
	return *t.Key
}

// PopulateDefaults recursively populates unset leaf fields in the Model_SingleKey
// with default values as specified in the YANG schema, instantiating any nil
// container fields.
func (t *Model_SingleKey) PopulateDefaults() {
	if t == nil {
		return
	}
	ygot.BuildEmptyTree(t)
}

// ΛListKeyMap returns the keys of the Model_SingleKey struct, which is a YANG list entry.
func (t *Model_SingleKey) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Key == nil {
		return nil, fmt.Errorf("nil value for key Key")
	}

	return map[string]interface{}{
		"key": *t.Key,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Model_SingleKey) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Model_SingleKey"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Model_SingleKey) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module in whose namespace
// Model_SingleKey belongs.
func (*Model_SingleKey) ΛBelongingModule() string {
	return "openconfig-withlist"
}

// Parent represents the /openconfig-simple/parent YANG schema element.
type Parent struct {
	Child *Parent_Child `path:"child" module:"openconfig-simple"`
}

// IsYANGGoStruct ensures that Parent implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Parent) IsYANGGoStruct() {}

// GetOrCreateChild retrieves the value of the Child field
// or returns the existing field if it already exists.
func (t *Parent) GetOrCreateChild() *Parent_Child {
	if t.Child != nil {
		return t.Child
	}
	t.Child = &Parent_Child{}
	return t.Child
}

// GetChild returns the value of the Child struct pointer
// from Parent. If the receiver or the field Child is nil, nil
// is returned such that the Get* methods can be safely chained.
func (t *Parent) GetChild() *Parent_Child {
	if t != nil && t.Child != nil {
		return t.Child
	}
	return nil
}

// PopulateDefaults recursively populates unset leaf fields in the Parent
// with default values as specified in the YANG schema, instantiating any nil
// container fields.
func (t *Parent) PopulateDefaults() {
	if t == nil {
		return
	}
	ygot.BuildEmptyTree(t)
	t.Child.PopulateDefaults()
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Parent) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Parent"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Parent) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module in whose namespace
// Parent belongs.
func (*Parent) ΛBelongingModule() string {
	return "openconfig-simple"
}

// Parent_Child represents the /openconfig-simple/parent/child YANG schema element.
type Parent_Child struct {
	Four  Binary        `path:"state/four" module:"openconfig-simple/openconfig-simple" shadow-path:"config/four" shadow-module:"openconfig-simple/openconfig-simple"`
	One   *string       `path:"state/one" module:"openconfig-simple/openconfig-simple" shadow-path:"config/one" shadow-module:"openconfig-simple/openconfig-simple"`
	Three E_Child_Three `path:"state/three" module:"openconfig-simple/openconfig-simple" shadow-path:"config/three" shadow-module:"openconfig-simple/openconfig-simple"`
	Two   *string       `path:"state/two" module:"openconfig-simple/openconfig-simple"`
}

// IsYANGGoStruct ensures that Parent_Child implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Parent_Child) IsYANGGoStruct() {}

// GetFour retrieves the value of the leaf Four from the Parent_Child
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Four is set, it can
// safely use t.GetFour() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Four == nil' before retrieving the leaf's value.
func (t *Parent_Child) GetFour() Binary {
	if t == nil || t.Four == nil {
		return nil
	}
	return t.Four
}

// GetOne retrieves the value of the leaf One from the Parent_Child
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if One is set, it can
// safely use t.GetOne() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.One == nil' before retrieving the leaf's value.
func (t *Parent_Child) GetOne() string {
	if t == nil || t.One == nil {
		return ""
	}
	return *t.One
}

// GetThree retrieves the value of the leaf Three from the Parent_Child
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Three is set, it can
// safely use t.GetThree() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Three == nil' before retrieving the leaf's value.
func (t *Parent_Child) GetThree() E_Child_Three {
	if t == nil || t.Three == 0 {
		return 0
	}
	return t.Three
}

// GetTwo retrieves the value of the leaf Two from the Parent_Child
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Two is set, it can
// safely use t.GetTwo() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Two == nil' before retrieving the leaf's value.
func (t *Parent_Child) GetTwo() string {
	if t == nil || t.Two == nil {
		return ""
	}
	return *t.Two
}

// PopulateDefaults recursively populates unset leaf fields in the Parent_Child
// with default values as specified in the YANG schema, instantiating any nil
// container fields.
func (t *Parent_Child) PopulateDefaults() {
	if t == nil {
		return
	}
	ygot.BuildEmptyTree(t)
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Parent_Child) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Parent_Child"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Parent_Child) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module in whose namespace
// Parent_Child belongs.
func (*Parent_Child) ΛBelongingModule() string {
	return "openconfig-simple"
}

// RemoteContainer represents the /openconfig-simple/remote-container YANG schema element.
type RemoteContainer struct {
	ALeaf *string `path:"state/a-leaf" module:"openconfig-simple/openconfig-simple" shadow-path:"config/a-leaf" shadow-module:"openconfig-simple/openconfig-simple"`
}

// IsYANGGoStruct ensures that RemoteContainer implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*RemoteContainer) IsYANGGoStruct() {}

// GetALeaf retrieves the value of the leaf ALeaf from the RemoteContainer
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if ALeaf is set, it can
// safely use t.GetALeaf() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.ALeaf == nil' before retrieving the leaf's value.
func (t *RemoteContainer) GetALeaf() string {
	if t == nil || t.ALeaf == nil {
		return ""
	}
	return *t.ALeaf
}

// PopulateDefaults recursively populates unset leaf fields in the RemoteContainer
// with default values as specified in the YANG schema, instantiating any nil
// container fields.
func (t *RemoteContainer) PopulateDefaults() {
	if t == nil {
		return
	}
	ygot.BuildEmptyTree(t)
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *RemoteContainer) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["RemoteContainer"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *RemoteContainer) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module in whose namespace
// RemoteContainer belongs.
func (*RemoteContainer) ΛBelongingModule() string {
	return "openconfig-simple"
}

// E_Child_Three is a derived int64 type which is used to represent
// the enumerated node Child_Three. An additional value named
// Child_Three_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_Child_Three int64

// IsYANGGoEnum ensures that Child_Three implements the yang.GoEnum
// interface. This ensures that Child_Three can be identified as a
// mapped type for a YANG enumeration.
func (E_Child_Three) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  Child_Three.
func (E_Child_Three) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum }

// String returns a logging-friendly string for E_Child_Three.
func (e E_Child_Three) String() string {
	return ygot.EnumLogString(e, int64(e), "E_Child_Three")
}

const (
	// Child_Three_UNSET corresponds to the value UNSET of Child_Three
	Child_Three_UNSET E_Child_Three = 0
	// Child_Three_ONE corresponds to the value ONE of Child_Three
	Child_Three_ONE E_Child_Three = 1
	// Child_Three_TWO corresponds to the value TWO of Child_Three
	Child_Three_TWO E_Child_Three = 2
)

// ΛEnum is a map, keyed by the name of the type defined for each enum in the
// generated Go code, which provides a mapping between the constant int64 value
// of each value of the enumeration, and the string that is used to represent it
// in the YANG schema. The map is named ΛEnum in order to avoid clash with any
// valid YANG identifier.
var ΛEnum = map[string]map[int64]ygot.EnumDefinition{
	"E_Child_Three": {
		1: {Name: "ONE"},
		2: {Name: "TWO"},
	},
}

var (
	// ySchema is a byte slice contain a gzip compressed representation of the
	// YANG schema from which the Go code was generated. When uncompressed the
	// contents of the byte slice is a JSON document containing an object, keyed
	// on the name of the generated struct, and containing the JSON marshalled
	// contents of a goyang yang.Entry struct, which defines the schema for the
	// fields within the struct.
	ySchema = []byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x1d, 0x5b, 0x6f, 0xe2, 0x38,
		0xf7, 0x9d, 0x5f, 0x11, 0xe5, 0xb9, 0x4c, 0x9a, 0x0c, 0x2d, 0x2d, 0x6f, 0xfd, 0xda, 0x19, 0x7d,
		0x52, 0xb7, 0xbb, 0x55, 0xbb, 0xda, 0x97, 0x9d, 0xd5, 0xc8, 0x04, 0x03, 0xd6, 0x24, 0x0e, 0xb2,
		0x9d, 0xb6, 0x68, 0xc5, 0x7f, 0x5f, 0x25, 0x81, 0x94, 0x4b, 0x2e, 0xb6, 0x13, 0x42, 0x80, 0xf3,
		0x58, 0xe2, 0xe3, 0x1c, 0x9f, 0xfb, 0xcd, 0xe9, 0xbf, 0x1d, 0xc3, 0x30, 0x0c, 0xf3, 0x77, 0xe4,
		0x63, 0x73, 0x60, 0x98, 0x23, 0xfc, 0x46, 0x5c, 0x6c, 0x5e, 0x24, 0xbf, 0x3e, 0x12, 0x3a, 0x32,
		0x07, 0x86, 0xbd, 0xfc, 0xf3, 0x3e, 0xa0, 0x63, 0x32, 0x31, 0x07, 0xc6, 0xe5, 0xf2, 0x87, 0x07,
		0xc2, 0xcc, 0x81, 0x91, 0x6c, 0x11, 0xff, 0xe0, 0x07, 0x23, 0xec, 0x6d, 0xfc, 0xb4, 0xb1, 0x7b,
		0xf2, 0xf8, 0x62, 0xf3, 0xe1, 0xe6, 0x4b, 0xd2, 0x9f, 0xb7, 0x5f, 0x96, 0x3e, 0x78, 0x66, 0x78,
		0x4c, 0x3e, 0x76, 0x5e, 0xb2, 0xf1, 0xa2, 0xc0, 0xdd, 0x7a, 0x4b, 0xfc, 0xf4, 0x35, 0x08, 0x99,
		0x8b, 0x33, 0x21, 0x13, 0x4c, 0xf0, 0xfc, 0x3d, 0x60, 0x11, 0x32, 0xe6, 0x2c, 0x79, 0xc9, 0x45,
		0xf6, 0xc2, 0xff, 0x23, 0x7e, 0xc7, 0x26, 0xa1, 0x8f, 0xa9, 0x30, 0x07, 0x86, 0x60, 0x21, 0xce,
		0x59, 0xb8, 0xb6, 0x2a, 0xc2, 0x69, 0x67, 0xd1, 0x62, 0xe3, 0x97, 0xc5, 0xd6, 0x49, 0xb7, 0xc9,
		0x9b, 0x3e, 0x40, 0xf9, 0x67, 0x58, 0x51, 0x00, 0xe5, 0xe1, 0x9e, 0x4d, 0xee, 0x52, 0xb2, 0xcb,
		0x90, 0x5f, 0x8e, 0x0d, 0xb2, 0xec, 0x50, 0x66, 0x8b, 0x32, 0x7b, 0xa4, 0xd9, 0x94, 0xcd, 0xae,
		0x1c, 0xb6, 0x95, 0xb2, 0x2f, 0x5d, 0xc0, 0x09, 0x9d, 0x78, 0xb8, 0xfb, 0x0b, 0xcf, 0xcb, 0x89,
		0xb0, 0x22, 0xe9, 0x1a, 0x4c, 0xc9, 0xa1, 0x8a, 0x19, 0x2d, 0xcd, 0x70, 0x15, 0xc6, 0xab, 0x09,
		0x80, 0xaa, 0x20, 0x68, 0x0b, 0x84, 0xb6, 0x60, 0x28, 0x0b, 0x48, 0xb1, 0xa0, 0x94, 0x08, 0x8c,
		0xb4, 0xe0, 0xa4, 0x0b, 0xdd, 0x15, 0xef, 0x24, 0x09, 0xb7, 0x62, 0xcb, 0x12, 0x4e, 0xf2, 0xf0,
		0x72, 0x82, 0xa4, 0x2c, 0x50, 0x3a, 0x82, 0xa5, 0x27, 0x60, 0xba, 0x82, 0x56, 0x59, 0xe0, 0x2a,
		0x0b, 0x9e, 0xb6, 0x00, 0xca, 0x09, 0xa2, 0xa4, 0x40, 0x2a, 0x0b, 0x66, 0x0a, 0x20, 0x63, 0xda,
		0x72, 0x79, 0x5b, 0x6e, 0xe3, 0xf2, 0x44, 0xf5, 0x52, 0x11, 0x4c, 0x55, 0x64, 0xab, 0x88, 0x6e,
		0x35, 0x11, 0xae, 0x2a, 0xca, 0xb5, 0x89, 0x74, 0x6d, 0xa2, 0x5d, 0x59, 0xc4, 0xd5, 0x44, 0x5d,
		0x51, 0xe4, 0x53, 0xec, 0xfe, 0x9c, 0xcf, 0x70, 0x35, 0x3e, 0x73, 0xc1, 0x08, 0x9d, 0xe8, 0xf0,
		0x7a, 0x65, 0x80, 0x6f, 0x3a, 0xfb, 0xa1, 0x47, 0xbd, 0x46, 0xe2, 0x8e, 0xd2, 0x40, 0x20, 0x41,
		0x02, 0xaa, 0x66, 0x2b, 0xb8, 0x3b, 0xc5, 0x3e, 0x9a, 0x21, 0x31, 0x8d, 0xa8, 0x65, 0x05, 0x33,
		0x4c, 0x13, 0x3f, 0xd5, 0x7d, 0x27, 0x62, 0xea, 0x11, 0x2e, 0xac, 0x38, 0x7f, 0xb0, 0x90, 0xf5,
		0x19, 0x04, 0x59, 0x4b, 0x57, 0xd6, 0xa9, 0xe7, 0x9c, 0x12, 0x67, 0x54, 0xb2, 0x69, 0x1a, 0xb6,
		0x4c, 0xd1, 0x86, 0x81, 0xbb, 0x3d, 0x5d, 0x77, 0xab, 0x6c, 0x73, 0x52, 0x3e, 0x79, 0x18, 0x8d,
		0x19, 0x1e, 0xab, 0x30, 0x6b, 0x65, 0x64, 0xfa, 0x0a, 0x30, 0xcf, 0x4b, 0x65, 0xfd, 0xf2, 0xc5,
		0xe2, 0x02, 0x09, 0x6c, 0x45, 0x62, 0xde, 0xa0, 0x2a, 0xc6, 0x2f, 0x55, 0x57, 0xc6, 0x04, 0x6c,
		0xcf, 0xd1, 0xaf, 0x03, 0xea, 0x08, 0xd1, 0x2f, 0x44, 0xbf, 0x10, 0xfd, 0x42, 0xf4, 0x7b, 0x90,
		0xe8, 0x57, 0xd5, 0xc4, 0xe8, 0x45, 0xad, 0x29, 0xfc, 0x7c, 0x12, 0x88, 0x6e, 0xe0, 0x76, 0xdd,
		0xc0, 0x9f, 0x31, 0xcc, 0x39, 0x1e, 0x75, 0x23, 0x27, 0x1c, 0x6d, 0xb6, 0x80, 0xb0, 0x7d, 0x27,
		0x6c, 0x4f, 0x5c, 0x70, 0x5d, 0xa1, 0x42, 0xa5, 0x6a, 0xdb, 0x63, 0x6c, 0xa5, 0x25, 0xec, 0xad,
		0xf9, 0x1b, 0xe1, 0xe2, 0x4e, 0x08, 0xc9, 0xe2, 0xdc, 0x13, 0xa1, 0xdf, 0x3c, 0x1c, 0xe9, 0x34,
		0x97, 0xb3, 0xad, 0xe6, 0x13, 0xfa, 0x58, 0x83, 0xb0, 0x6f, 0x7a, 0xbd, 0xeb, 0x7e, 0xaf, 0x77,
		0xd9, 0xff, 0xda, 0xbf, 0xbc, 0xbd, 0xba, 0xb2, 0xaf, 0xed, 0x2b, 0x89, 0x4d, 0xfe, 0x60, 0x23,
		0xcc, 0xf0, 0xe8, 0x7f, 0xd1, 0xa1, 0x68, 0xe8, 0x79, 0x95, 0x68, 0xa3, 0x28, 0x14, 0x7a, 0xc2,
		0x60, 0x4a, 0x45, 0x7a, 0x2c, 0x74, 0x05, 0x5d, 0x1a, 0x93, 0xa7, 0x68, 0x8f, 0x9f, 0xaf, 0xf1,
		0x0e, 0x8f, 0x65, 0x21, 0xe7, 0xa2, 0xa6, 0x72, 0xbe, 0x24, 0x2d, 0x14, 0x68, 0x90, 0x8d, 0xf7,
		0x2e, 0x56, 0x19, 0x18, 0x99, 0xc3, 0xf2, 0x16, 0xd0, 0x10, 0x5a, 0x40, 0xad, 0x6f, 0x01, 0xf9,
		0xa1, 0x27, 0x88, 0x5a, 0x07, 0xe8, 0x13, 0x04, 0x1a, 0x40, 0xd0, 0x00, 0x82, 0x06, 0x10, 0xa4,
		0xc0, 0xed, 0x4e, 0x81, 0xed, 0x4a, 0x39, 0xb0, 0x0d, 0x49, 0x30, 0x24, 0xc1, 0xa7, 0x92, 0x04,
		0x87, 0x84, 0x8a, 0xaf, 0x4e, 0x85, 0x24, 0xb8, 0xaf, 0x01, 0xfa, 0x82, 0xe8, 0x24, 0x7a, 0xfb,
		0xdf, 0x5a, 0x3c, 0xd1, 0x93, 0xad, 0x55, 0x02, 0xa4, 0x2d, 0x9c, 0xe9, 0x26, 0x7f, 0x21, 0x2f,
		0xc4, 0xea, 0x6a, 0xb9, 0xb3, 0xcf, 0x77, 0x86, 0xdc, 0x28, 0x76, 0x7f, 0x20, 0x13, 0x22, 0x9b,
		0x90, 0x15, 0xf3, 0x14, 0x4f, 0x90, 0x20, 0x6f, 0x11, 0x6e, 0x63, 0xe4, 0x71, 0xac, 0xbd, 0xdb,
		0xe2, 0xa2, 0x02, 0x89, 0xd1, 0x47, 0x7d, 0x24, 0xee, 0x39, 0xb7, 0xbd, 0xdb, 0xeb, 0xbe, 0x73,
		0x7b, 0x75, 0xba, 0xb4, 0xee, 0x34, 0x03, 0xf5, 0xcf, 0xbe, 0x4a, 0x3e, 0x17, 0x4a, 0xae, 0xd7,
		0xa9, 0xe4, 0x7a, 0x1d, 0x70, 0xbd, 0xe0, 0x7a, 0x4f, 0xc9, 0xf5, 0x5e, 0xf7, 0x2a, 0xb8, 0xde,
		0x1b, 0x70, 0xbd, 0xe0, 0x7a, 0xf7, 0xe5, 0x7a, 0xf5, 0x6a, 0xbd, 0xe0, 0x84, 0x0f, 0xe3, 0x84,
		0x8f, 0xab, 0xef, 0x32, 0xb4, 0xd2, 0x8a, 0xe1, 0x61, 0xa6, 0xa5, 0x6c, 0xad, 0x71, 0x29, 0x1b,
		0xe6, 0xa5, 0xa0, 0x3a, 0xa5, 0xa6, 0x4a, 0x47, 0x39, 0x2f, 0x65, 0x37, 0xac, 0x8d, 0x8e, 0x96,
		0x36, 0x3a, 0xa0, 0x8d, 0xa0, 0x8d, 0x67, 0xa0, 0x8d, 0x0e, 0x8c, 0x2f, 0xc2, 0xf8, 0xe2, 0x69,
		0xea, 0x23, 0xf4, 0x6e, 0xa0, 0x80, 0x04, 0x05, 0xa4, 0x4a, 0x05, 0x24, 0xe8, 0xdd, 0x40, 0x01,
		0xa9, 0x9d, 0x05, 0x24, 0xe8, 0xdd, 0x1c, 0xaa, 0x6c, 0x74, 0x06, 0x73, 0xc6, 0xd0, 0x74, 0x82,
		0x98, 0x01, 0x62, 0x06, 0xcd, 0x98, 0x01, 0x9a, 0x4e, 0x10, 0x33, 0xb4, 0x33, 0x66, 0x80, 0xa6,
		0x13, 0x44, 0x0f, 0x70, 0x4b, 0xa9, 0xa0, 0x5b, 0xd6, 0xca, 0x4b, 0x4a, 0xf6, 0x0f, 0xfa, 0x83,
		0x1a, 0x12, 0x91, 0x12, 0x5c, 0x57, 0xda, 0x8b, 0x54, 0xe8, 0xde, 0x56, 0x7a, 0x8a, 0x36, 0x38,
		0xde, 0xcb, 0x4a, 0x43, 0xe9, 0xcb, 0x4a, 0x85, 0x9f, 0xb4, 0x2b, 0xc1, 0x4b, 0x1a, 0x9f, 0xac,
		0xcf, 0xfb, 0x65, 0x50, 0x7d, 0x13, 0xe9, 0x4f, 0xd4, 0xd6, 0xd0, 0x32, 0x67, 0x88, 0x25, 0x21,
		0x68, 0xce, 0x47, 0x0b, 0x97, 0xcf, 0x1b, 0xf9, 0x6a, 0x21, 0x6f, 0xe3, 0x67, 0x0b, 0x79, 0x6d,
		0xdf, 0x2d, 0x74, 0xa7, 0xc4, 0x1b, 0x95, 0x5f, 0x5c, 0x4b, 0x96, 0xb5, 0xe2, 0xf2, 0x1a, 0x3f,
		0xc6, 0xdb, 0x6b, 0xbc, 0xb1, 0xeb, 0x6b, 0x92, 0xf7, 0x8f, 0xd4, 0xee, 0x1d, 0xb5, 0xe4, 0xe2,
		0x1a, 0x3f, 0xc5, 0x9b, 0x6b, 0xbc, 0x35, 0x57, 0xd7, 0xc6, 0x41, 0xc8, 0xd4, 0x7b, 0x9f, 0x31,
		0xd4, 0x49, 0x8c, 0x22, 0xf0, 0x73, 0xec, 0x7d, 0xf2, 0xe3, 0x1b, 0x46, 0x18, 0x12, 0x8a, 0xd8,
		0x5c, 0x63, 0x16, 0xe1, 0xb6, 0xc1, 0x49, 0x82, 0x80, 0x6a, 0xcc, 0x11, 0x44, 0x40, 0xa0, 0x4a,
		0xa0, 0x4a, 0x8d, 0xa9, 0x92, 0xf2, 0x37, 0x60, 0x14, 0xbf, 0xfd, 0x52, 0x8f, 0x2e, 0x89, 0x29,
		0xc3, 0x1a, 0xda, 0x94, 0x80, 0x81, 0x3e, 0x81, 0x3e, 0x35, 0xa6, 0x4f, 0x98, 0x86, 0x3e, 0x66,
		0x49, 0x36, 0xad, 0xa1, 0x54, 0x3d, 0x05, 0x98, 0x6f, 0x34, 0xf4, 0xe5, 0xab, 0x84, 0xfb, 0xae,
		0x86, 0xd5, 0x57, 0xe7, 0xe1, 0xc4, 0x9f, 0x79, 0xd8, 0x4a, 0x72, 0x7c, 0x2b, 0x4e, 0x3c, 0xa5,
		0x86, 0xe4, 0x0b, 0xea, 0x34, 0x05, 0x09, 0xa3, 0xdc, 0xc0, 0x9f, 0xd2, 0xa0, 0x9f, 0x72, 0xb2,
		0xe4, 0x40, 0xb2, 0x04, 0xc9, 0x12, 0x78, 0x24, 0xf0, 0x48, 0xc7, 0x98, 0x2c, 0xed, 0xb9, 0x4b,
		0x54, 0xb9, 0x3d, 0x06, 0xd9, 0x1c, 0xe8, 0x3a, 0x64, 0x73, 0x35, 0x65, 0x73, 0xe7, 0xa1, 0xec,
		0x90, 0x6e, 0x82, 0xc2, 0x43, 0xba, 0x59, 0x2d, 0xdd, 0x3c, 0x13, 0x4b, 0xf1, 0x1e, 0x68, 0xd8,
		0x89, 0xf7, 0x00, 0xac, 0x04, 0x58, 0x89, 0xb3, 0x2a, 0xf2, 0xb6, 0xb8, 0xb6, 0x24, 0x31, 0x52,
		0xd6, 0x9e, 0x11, 0xa0, 0x8c, 0x03, 0x98, 0x85, 0xd5, 0xad, 0xf5, 0xf9, 0x9b, 0xe7, 0x18, 0xea,
		0xe7, 0x7d, 0x0c, 0x75, 0xe0, 0xd9, 0xa1, 0x8d, 0x83, 0x94, 0x8f, 0x0e, 0x25, 0xa8, 0xcb, 0xcc,
		0x0e, 0x31, 0xec, 0x07, 0x02, 0x77, 0xdd, 0x80, 0x0a, 0x44, 0x28, 0x66, 0xf9, 0x53, 0x44, 0x3b,
		0x2b, 0x1b, 0x99, 0x27, 0x62, 0x6d, 0x9c, 0x27, 0x62, 0xf5, 0xcd, 0x13, 0x15, 0x8f, 0x9f, 0xc8,
		0x8d, 0x9d, 0x34, 0x3c, 0x51, 0xc4, 0x8e, 0x71, 0xa2, 0x88, 0x35, 0x36, 0x51, 0x84, 0xd2, 0xd0,
		0x4a, 0xae, 0x46, 0xbe, 0x5c, 0x2f, 0x57, 0x24, 0xbf, 0x3c, 0xec, 0x44, 0x11, 0x3b, 0xc5, 0x22,
		0x39, 0xdb, 0x77, 0x91, 0x5c, 0x3a, 0x14, 0x51, 0x0f, 0x41, 0x24, 0x43, 0x8f, 0xd6, 0x79, 0xe4,
		0x6d, 0x67, 0x52, 0xd8, 0xb2, 0x92, 0xfb, 0x7f, 0x02, 0xc5, 0xad, 0x29, 0xa9, 0x96, 0x94, 0xb4,
		0x21, 0x75, 0xc0, 0x90, 0x82, 0x21, 0x05, 0x43, 0x7a, 0x86, 0x86, 0xb4, 0xe6, 0xdc, 0x4b, 0xbb,
		0x30, 0xd3, 0x7e, 0x8b, 0x5e, 0x90, 0x28, 0x36, 0x9e, 0x37, 0x95, 0xe4, 0x2e, 0x19, 0x19, 0xd4,
		0x4b, 0x0c, 0x71, 0x9f, 0x02, 0xe4, 0xa5, 0x52, 0x9d, 0x35, 0x7c, 0xf3, 0xf0, 0x34, 0x09, 0xbf,
		0x4f, 0xf9, 0xfb, 0x1a, 0xe3, 0xba, 0xa3, 0x66, 0x26, 0xe1, 0xdf, 0xd1, 0x2f, 0xfc, 0x12, 0x04,
		0xbb, 0x2a, 0xb8, 0x7d, 0x3e, 0x73, 0xfd, 0xd1, 0x06, 0xd6, 0x0f, 0xf8, 0x8d, 0xb8, 0x4b, 0xa2,
		0x2f, 0x3a, 0x8b, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x57,
		0x87, 0xca, 0x1b, 0x83, 0x00, 0x00,
	}
)

// ΛEnumTypes is a map, keyed by a YANG schema path, of the enumerated types that
// correspond with the leaf. The type is represented as a reflect.Type. The naming
// of the map ensures that there are no clashes with valid YANG identifiers.
var ΛEnumTypes = map[string][]reflect.Type{
	"/parent/child/state/three": []reflect.Type{
		reflect.TypeOf((E_Child_Three)(0)),
	},
}
