run:
  timeout: 10m
  skip-dirs:
    - pathgen/testdata
    - exampleoc
    - internal/examplesetorigin

linters:
  enable:
    - gofmt
    - revive
    - goimports

linters-settings:
  revive:
    confidence: 0.8
    rules:
    - name: error-strings
    - name: exported

issues:
  exclude:
    - receiver-naming # This appears to broken with generics.
  exclude-use-default: false
  exclude-rules:
    # Exclude naming complaints from schema.
    - path: internal/testutil
      linters: revive
    # Adding a package comment breaks other linters
    - path: ygnmi/types.go
      linters: unused

