version: "2"
linters:
  enable:
    - revive
  settings:
    revive:
      confidence: 0.8
      rules:
        - name: error-strings
        - name: exported
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        path: internal/testutil
      - linters:
          - unused
        path: ygnmi/types.go
      - path: (.+)\.go$
        text: receiver-naming
    paths:
      - pathgen/testdata
      - exampleoc
      - internal/examplesetorigin
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - pathgen/testdata
      - exampleoc
      - internal/examplesetorigin
      - third_party$
      - builtin$
      - examples$
