run:
  timeout: 5m
  skip-dirs:
    - exampleoc

linters:
  enable:
    - gofmt
    - revive
    - goimports

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude naming complaints from schema.
    - path: internal/testutil
      linters: revive
