// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
Package uexampleoc is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by ygnmi version: (devel): (ygot: v0.29.12)
using the following YANG input files:
  - ../../pathgen/testdata/yang/openconfig-simple.yang
  - ../../pathgen/testdata/yang/openconfig-withlistval.yang
  - ../../pathgen/testdata/yang/openconfig-nested.yang

Imported modules were sourced from:
*/
package uexampleoc

import (
	"github.com/openconfig/ygot/ygot"
)

// E_Simple_Parent_Child_Config_Three is a derived int64 type which is used to represent
// the enumerated node Simple_Parent_Child_Config_Three. An additional value named
// Simple_Parent_Child_Config_Three_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_Simple_Parent_Child_Config_Three int64

// IsYANGGoEnum ensures that Simple_Parent_Child_Config_Three implements the yang.GoEnum
// interface. This ensures that Simple_Parent_Child_Config_Three can be identified as a
// mapped type for a YANG enumeration.
func (E_Simple_Parent_Child_Config_Three) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  Simple_Parent_Child_Config_Three.
func (E_Simple_Parent_Child_Config_Three) ΛMap() map[string]map[int64]ygot.EnumDefinition {
	return ΛEnum
}

// String returns a logging-friendly string for E_Simple_Parent_Child_Config_Three.
func (e E_Simple_Parent_Child_Config_Three) String() string {
	return ygot.EnumLogString(e, int64(e), "E_Simple_Parent_Child_Config_Three")
}

const (
	// Simple_Parent_Child_Config_Three_UNSET corresponds to the value UNSET of Simple_Parent_Child_Config_Three
	Simple_Parent_Child_Config_Three_UNSET E_Simple_Parent_Child_Config_Three = 0
	// Simple_Parent_Child_Config_Three_ONE corresponds to the value ONE of Simple_Parent_Child_Config_Three
	Simple_Parent_Child_Config_Three_ONE E_Simple_Parent_Child_Config_Three = 1
	// Simple_Parent_Child_Config_Three_TWO corresponds to the value TWO of Simple_Parent_Child_Config_Three
	Simple_Parent_Child_Config_Three_TWO E_Simple_Parent_Child_Config_Three = 2
)
