// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
Package simple is a generated package which contains definitions
of structs which generate gNMI paths for a YANG schema.

This package was generated by ygnmi version: (devel): (ygot: (devel))
using the following YANG input files:
  - ../../pathgen/testdata/yang/openconfig-simple.yang
  - ../../pathgen/testdata/yang/openconfig-withlistval.yang
  - ../../pathgen/testdata/yang/openconfig-nested.yang

Imported modules were sourced from:
*/
package simple

import (
	"reflect"

	oc "github.com/openconfig/ygnmi/internal/uexampleoc"
	"github.com/openconfig/ygnmi/ygnmi"
	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/ygot/ytypes"
)

// OpenconfigSimple_ParentPath represents the /openconfig-simple/parent YANG schema element.
type OpenconfigSimple_ParentPath struct {
	*ygnmi.NodePath
}

// OpenconfigSimple_ParentPathAny represents the wildcard version of the /openconfig-simple/parent YANG schema element.
type OpenconfigSimple_ParentPathAny struct {
	*ygnmi.NodePath
}

// Child (container):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "child"
//	Path from root:       "/parent/child"
func (n *OpenconfigSimple_ParentPath) Child() *OpenconfigSimple_Parent_ChildPath {
	return &OpenconfigSimple_Parent_ChildPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"child"},
			map[string]interface{}{},
			n,
		),
	}
}

// Child (container):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "child"
//	Path from root:       "/parent/child"
func (n *OpenconfigSimple_ParentPathAny) Child() *OpenconfigSimple_Parent_ChildPathAny {
	return &OpenconfigSimple_Parent_ChildPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"child"},
			map[string]interface{}{},
			n,
		),
	}
}

func binarySliceToFloatSlice(in []oc.Binary) []float32 {
	converted := make([]float32, 0, len(in))
	for _, binary := range in {
		converted = append(converted, ygot.BinaryToFloat32(binary))
	}
	return converted
}

// Query returns a Query that can be used in gNMI operations.
func (n *OpenconfigSimple_ParentPath) Query() ygnmi.ConfigQuery[*oc.OpenconfigSimple_Parent] {
	return ygnmi.NewConfigQuery[*oc.OpenconfigSimple_Parent](
		"OpenconfigSimple_Parent",
		false,
		false,
		false,
		false,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
func (n *OpenconfigSimple_ParentPathAny) Query() ygnmi.WildcardQuery[*oc.OpenconfigSimple_Parent] {
	return ygnmi.NewWildcardQuery[*oc.OpenconfigSimple_Parent](
		"OpenconfigSimple_Parent",
		false,
		false,
		false,
		false,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}

// OpenconfigSimple_Parent_ChildPath represents the /openconfig-simple/parent/child YANG schema element.
type OpenconfigSimple_Parent_ChildPath struct {
	*ygnmi.NodePath
}

// OpenconfigSimple_Parent_ChildPathAny represents the wildcard version of the /openconfig-simple/parent/child YANG schema element.
type OpenconfigSimple_Parent_ChildPathAny struct {
	*ygnmi.NodePath
}

// Config (container):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "config"
//	Path from root:       "/parent/child/config"
func (n *OpenconfigSimple_Parent_ChildPath) Config() *OpenconfigSimple_Parent_Child_ConfigPath {
	return &OpenconfigSimple_Parent_Child_ConfigPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"config"},
			map[string]interface{}{},
			n,
		),
	}
}

// Config (container):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "config"
//	Path from root:       "/parent/child/config"
func (n *OpenconfigSimple_Parent_ChildPathAny) Config() *OpenconfigSimple_Parent_Child_ConfigPathAny {
	return &OpenconfigSimple_Parent_Child_ConfigPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"config"},
			map[string]interface{}{},
			n,
		),
	}
}

// State (container):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "state"
//	Path from root:       "/parent/child/state"
func (n *OpenconfigSimple_Parent_ChildPath) State() *OpenconfigSimple_Parent_Child_StatePath {
	return &OpenconfigSimple_Parent_Child_StatePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state"},
			map[string]interface{}{},
			n,
		),
	}
}

// State (container):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "state"
//	Path from root:       "/parent/child/state"
func (n *OpenconfigSimple_Parent_ChildPathAny) State() *OpenconfigSimple_Parent_Child_StatePathAny {
	return &OpenconfigSimple_Parent_Child_StatePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state"},
			map[string]interface{}{},
			n,
		),
	}
}

// Query returns a Query that can be used in gNMI operations.
func (n *OpenconfigSimple_Parent_ChildPath) Query() ygnmi.ConfigQuery[*oc.OpenconfigSimple_Parent_Child] {
	return ygnmi.NewConfigQuery[*oc.OpenconfigSimple_Parent_Child](
		"OpenconfigSimple_Parent_Child",
		false,
		false,
		false,
		false,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
func (n *OpenconfigSimple_Parent_ChildPathAny) Query() ygnmi.WildcardQuery[*oc.OpenconfigSimple_Parent_Child] {
	return ygnmi.NewWildcardQuery[*oc.OpenconfigSimple_Parent_Child](
		"OpenconfigSimple_Parent_Child",
		false,
		false,
		false,
		false,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}

// OpenconfigSimple_Parent_Child_Config_FivePath represents the /openconfig-simple/parent/child/config/five YANG schema element.
type OpenconfigSimple_Parent_Child_Config_FivePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// OpenconfigSimple_Parent_Child_Config_FivePathAny represents the wildcard version of the /openconfig-simple/parent/child/config/five YANG schema element.
type OpenconfigSimple_Parent_Child_Config_FivePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "five"
//	Path from root:       "/parent/child/config/five"
func (n *OpenconfigSimple_Parent_Child_Config_FivePath) Query() ygnmi.ConfigQuery[float32] {
	return ygnmi.NewConfigQuery[float32](
		"OpenconfigSimple_Parent_Child_Config",
		false,
		true,
		false,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"five"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (float32, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_Config).Five
			return ygot.BinaryToFloat32(ret), !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_Config) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "five"
//	Path from root:       "/parent/child/config/five"
func (n *OpenconfigSimple_Parent_Child_Config_FivePathAny) Query() ygnmi.WildcardQuery[float32] {
	return ygnmi.NewWildcardQuery[float32](
		"OpenconfigSimple_Parent_Child_Config",
		false,
		true,
		false,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"five"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (float32, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_Config).Five
			return ygot.BinaryToFloat32(ret), !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_Config) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}

// OpenconfigSimple_Parent_Child_Config_FourPath represents the /openconfig-simple/parent/child/config/four YANG schema element.
type OpenconfigSimple_Parent_Child_Config_FourPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// OpenconfigSimple_Parent_Child_Config_FourPathAny represents the wildcard version of the /openconfig-simple/parent/child/config/four YANG schema element.
type OpenconfigSimple_Parent_Child_Config_FourPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "four"
//	Path from root:       "/parent/child/config/four"
func (n *OpenconfigSimple_Parent_Child_Config_FourPath) Query() ygnmi.ConfigQuery[oc.Binary] {
	return ygnmi.NewConfigQuery[oc.Binary](
		"OpenconfigSimple_Parent_Child_Config",
		false,
		true,
		false,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"four"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.Binary, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_Config).Four
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_Config) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "four"
//	Path from root:       "/parent/child/config/four"
func (n *OpenconfigSimple_Parent_Child_Config_FourPathAny) Query() ygnmi.WildcardQuery[oc.Binary] {
	return ygnmi.NewWildcardQuery[oc.Binary](
		"OpenconfigSimple_Parent_Child_Config",
		false,
		true,
		false,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"four"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.Binary, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_Config).Four
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_Config) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}

// OpenconfigSimple_Parent_Child_Config_OnePath represents the /openconfig-simple/parent/child/config/one YANG schema element.
type OpenconfigSimple_Parent_Child_Config_OnePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// OpenconfigSimple_Parent_Child_Config_OnePathAny represents the wildcard version of the /openconfig-simple/parent/child/config/one YANG schema element.
type OpenconfigSimple_Parent_Child_Config_OnePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "one"
//	Path from root:       "/parent/child/config/one"
func (n *OpenconfigSimple_Parent_Child_Config_OnePath) Query() ygnmi.ConfigQuery[string] {
	return ygnmi.NewConfigQuery[string](
		"OpenconfigSimple_Parent_Child_Config",
		false,
		true,
		true,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"one"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_Config).One
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_Config) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "one"
//	Path from root:       "/parent/child/config/one"
func (n *OpenconfigSimple_Parent_Child_Config_OnePathAny) Query() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"OpenconfigSimple_Parent_Child_Config",
		false,
		true,
		true,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"one"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_Config).One
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_Config) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}

// OpenconfigSimple_Parent_Child_Config_SixPath represents the /openconfig-simple/parent/child/config/six YANG schema element.
type OpenconfigSimple_Parent_Child_Config_SixPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// OpenconfigSimple_Parent_Child_Config_SixPathAny represents the wildcard version of the /openconfig-simple/parent/child/config/six YANG schema element.
type OpenconfigSimple_Parent_Child_Config_SixPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "six"
//	Path from root:       "/parent/child/config/six"
func (n *OpenconfigSimple_Parent_Child_Config_SixPath) Query() ygnmi.ConfigQuery[[]float32] {
	return ygnmi.NewConfigQuery[[]float32](
		"OpenconfigSimple_Parent_Child_Config",
		false,
		true,
		false,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"six"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]float32, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_Config).Six
			return binarySliceToFloatSlice(ret), !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_Config) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "six"
//	Path from root:       "/parent/child/config/six"
func (n *OpenconfigSimple_Parent_Child_Config_SixPathAny) Query() ygnmi.WildcardQuery[[]float32] {
	return ygnmi.NewWildcardQuery[[]float32](
		"OpenconfigSimple_Parent_Child_Config",
		false,
		true,
		false,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"six"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]float32, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_Config).Six
			return binarySliceToFloatSlice(ret), !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_Config) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}

// OpenconfigSimple_Parent_Child_Config_ThreePath represents the /openconfig-simple/parent/child/config/three YANG schema element.
type OpenconfigSimple_Parent_Child_Config_ThreePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// OpenconfigSimple_Parent_Child_Config_ThreePathAny represents the wildcard version of the /openconfig-simple/parent/child/config/three YANG schema element.
type OpenconfigSimple_Parent_Child_Config_ThreePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "three"
//	Path from root:       "/parent/child/config/three"
func (n *OpenconfigSimple_Parent_Child_Config_ThreePath) Query() ygnmi.ConfigQuery[oc.E_Simple_Parent_Child_Config_Three] {
	return ygnmi.NewConfigQuery[oc.E_Simple_Parent_Child_Config_Three](
		"OpenconfigSimple_Parent_Child_Config",
		false,
		true,
		false,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"three"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_Simple_Parent_Child_Config_Three, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_Config).Three
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_Config) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "three"
//	Path from root:       "/parent/child/config/three"
func (n *OpenconfigSimple_Parent_Child_Config_ThreePathAny) Query() ygnmi.WildcardQuery[oc.E_Simple_Parent_Child_Config_Three] {
	return ygnmi.NewWildcardQuery[oc.E_Simple_Parent_Child_Config_Three](
		"OpenconfigSimple_Parent_Child_Config",
		false,
		true,
		false,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"three"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_Simple_Parent_Child_Config_Three, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_Config).Three
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_Config) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}

// OpenconfigSimple_Parent_Child_ConfigPath represents the /openconfig-simple/parent/child/config YANG schema element.
type OpenconfigSimple_Parent_Child_ConfigPath struct {
	*ygnmi.NodePath
}

// OpenconfigSimple_Parent_Child_ConfigPathAny represents the wildcard version of the /openconfig-simple/parent/child/config YANG schema element.
type OpenconfigSimple_Parent_Child_ConfigPathAny struct {
	*ygnmi.NodePath
}

// Five (leaf):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "five"
//	Path from root:       "/parent/child/config/five"
func (n *OpenconfigSimple_Parent_Child_ConfigPath) Five() *OpenconfigSimple_Parent_Child_Config_FivePath {
	return &OpenconfigSimple_Parent_Child_Config_FivePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"five"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Five (leaf):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "five"
//	Path from root:       "/parent/child/config/five"
func (n *OpenconfigSimple_Parent_Child_ConfigPathAny) Five() *OpenconfigSimple_Parent_Child_Config_FivePathAny {
	return &OpenconfigSimple_Parent_Child_Config_FivePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"five"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Four (leaf):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "four"
//	Path from root:       "/parent/child/config/four"
func (n *OpenconfigSimple_Parent_Child_ConfigPath) Four() *OpenconfigSimple_Parent_Child_Config_FourPath {
	return &OpenconfigSimple_Parent_Child_Config_FourPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"four"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Four (leaf):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "four"
//	Path from root:       "/parent/child/config/four"
func (n *OpenconfigSimple_Parent_Child_ConfigPathAny) Four() *OpenconfigSimple_Parent_Child_Config_FourPathAny {
	return &OpenconfigSimple_Parent_Child_Config_FourPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"four"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// One (leaf):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "one"
//	Path from root:       "/parent/child/config/one"
func (n *OpenconfigSimple_Parent_Child_ConfigPath) One() *OpenconfigSimple_Parent_Child_Config_OnePath {
	return &OpenconfigSimple_Parent_Child_Config_OnePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"one"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// One (leaf):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "one"
//	Path from root:       "/parent/child/config/one"
func (n *OpenconfigSimple_Parent_Child_ConfigPathAny) One() *OpenconfigSimple_Parent_Child_Config_OnePathAny {
	return &OpenconfigSimple_Parent_Child_Config_OnePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"one"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Six (leaf-list):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "six"
//	Path from root:       "/parent/child/config/six"
func (n *OpenconfigSimple_Parent_Child_ConfigPath) Six() *OpenconfigSimple_Parent_Child_Config_SixPath {
	return &OpenconfigSimple_Parent_Child_Config_SixPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"six"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Six (leaf-list):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "six"
//	Path from root:       "/parent/child/config/six"
func (n *OpenconfigSimple_Parent_Child_ConfigPathAny) Six() *OpenconfigSimple_Parent_Child_Config_SixPathAny {
	return &OpenconfigSimple_Parent_Child_Config_SixPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"six"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Three (leaf):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "three"
//	Path from root:       "/parent/child/config/three"
func (n *OpenconfigSimple_Parent_Child_ConfigPath) Three() *OpenconfigSimple_Parent_Child_Config_ThreePath {
	return &OpenconfigSimple_Parent_Child_Config_ThreePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"three"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Three (leaf):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "three"
//	Path from root:       "/parent/child/config/three"
func (n *OpenconfigSimple_Parent_Child_ConfigPathAny) Three() *OpenconfigSimple_Parent_Child_Config_ThreePathAny {
	return &OpenconfigSimple_Parent_Child_Config_ThreePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"three"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Query returns a Query that can be used in gNMI operations.
func (n *OpenconfigSimple_Parent_Child_ConfigPath) Query() ygnmi.ConfigQuery[*oc.OpenconfigSimple_Parent_Child_Config] {
	return ygnmi.NewConfigQuery[*oc.OpenconfigSimple_Parent_Child_Config](
		"OpenconfigSimple_Parent_Child_Config",
		false,
		false,
		false,
		false,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
func (n *OpenconfigSimple_Parent_Child_ConfigPathAny) Query() ygnmi.WildcardQuery[*oc.OpenconfigSimple_Parent_Child_Config] {
	return ygnmi.NewWildcardQuery[*oc.OpenconfigSimple_Parent_Child_Config](
		"OpenconfigSimple_Parent_Child_Config",
		false,
		false,
		false,
		false,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}

// OpenconfigSimple_Parent_Child_State_FivePath represents the /openconfig-simple/parent/child/state/five YANG schema element.
type OpenconfigSimple_Parent_Child_State_FivePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// OpenconfigSimple_Parent_Child_State_FivePathAny represents the wildcard version of the /openconfig-simple/parent/child/state/five YANG schema element.
type OpenconfigSimple_Parent_Child_State_FivePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "five"
//	Path from root:       "/parent/child/state/five"
func (n *OpenconfigSimple_Parent_Child_State_FivePath) Query() ygnmi.ConfigQuery[float32] {
	return ygnmi.NewConfigQuery[float32](
		"OpenconfigSimple_Parent_Child_State",
		false,
		true,
		false,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"five"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (float32, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_State).Five
			return ygot.BinaryToFloat32(ret), !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "five"
//	Path from root:       "/parent/child/state/five"
func (n *OpenconfigSimple_Parent_Child_State_FivePathAny) Query() ygnmi.WildcardQuery[float32] {
	return ygnmi.NewWildcardQuery[float32](
		"OpenconfigSimple_Parent_Child_State",
		false,
		true,
		false,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"five"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (float32, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_State).Five
			return ygot.BinaryToFloat32(ret), !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}

// OpenconfigSimple_Parent_Child_State_FourPath represents the /openconfig-simple/parent/child/state/four YANG schema element.
type OpenconfigSimple_Parent_Child_State_FourPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// OpenconfigSimple_Parent_Child_State_FourPathAny represents the wildcard version of the /openconfig-simple/parent/child/state/four YANG schema element.
type OpenconfigSimple_Parent_Child_State_FourPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "four"
//	Path from root:       "/parent/child/state/four"
func (n *OpenconfigSimple_Parent_Child_State_FourPath) Query() ygnmi.ConfigQuery[oc.Binary] {
	return ygnmi.NewConfigQuery[oc.Binary](
		"OpenconfigSimple_Parent_Child_State",
		false,
		true,
		false,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"four"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.Binary, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_State).Four
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "four"
//	Path from root:       "/parent/child/state/four"
func (n *OpenconfigSimple_Parent_Child_State_FourPathAny) Query() ygnmi.WildcardQuery[oc.Binary] {
	return ygnmi.NewWildcardQuery[oc.Binary](
		"OpenconfigSimple_Parent_Child_State",
		false,
		true,
		false,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"four"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.Binary, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_State).Four
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}

// OpenconfigSimple_Parent_Child_State_OnePath represents the /openconfig-simple/parent/child/state/one YANG schema element.
type OpenconfigSimple_Parent_Child_State_OnePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// OpenconfigSimple_Parent_Child_State_OnePathAny represents the wildcard version of the /openconfig-simple/parent/child/state/one YANG schema element.
type OpenconfigSimple_Parent_Child_State_OnePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "one"
//	Path from root:       "/parent/child/state/one"
func (n *OpenconfigSimple_Parent_Child_State_OnePath) Query() ygnmi.ConfigQuery[string] {
	return ygnmi.NewConfigQuery[string](
		"OpenconfigSimple_Parent_Child_State",
		false,
		true,
		true,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"one"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_State).One
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "one"
//	Path from root:       "/parent/child/state/one"
func (n *OpenconfigSimple_Parent_Child_State_OnePathAny) Query() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"OpenconfigSimple_Parent_Child_State",
		false,
		true,
		true,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"one"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_State).One
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}

// OpenconfigSimple_Parent_Child_State_SixPath represents the /openconfig-simple/parent/child/state/six YANG schema element.
type OpenconfigSimple_Parent_Child_State_SixPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// OpenconfigSimple_Parent_Child_State_SixPathAny represents the wildcard version of the /openconfig-simple/parent/child/state/six YANG schema element.
type OpenconfigSimple_Parent_Child_State_SixPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "six"
//	Path from root:       "/parent/child/state/six"
func (n *OpenconfigSimple_Parent_Child_State_SixPath) Query() ygnmi.ConfigQuery[[]float32] {
	return ygnmi.NewConfigQuery[[]float32](
		"OpenconfigSimple_Parent_Child_State",
		false,
		true,
		false,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"six"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]float32, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_State).Six
			return binarySliceToFloatSlice(ret), !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "six"
//	Path from root:       "/parent/child/state/six"
func (n *OpenconfigSimple_Parent_Child_State_SixPathAny) Query() ygnmi.WildcardQuery[[]float32] {
	return ygnmi.NewWildcardQuery[[]float32](
		"OpenconfigSimple_Parent_Child_State",
		false,
		true,
		false,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"six"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]float32, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_State).Six
			return binarySliceToFloatSlice(ret), !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}

// OpenconfigSimple_Parent_Child_State_ThreePath represents the /openconfig-simple/parent/child/state/three YANG schema element.
type OpenconfigSimple_Parent_Child_State_ThreePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// OpenconfigSimple_Parent_Child_State_ThreePathAny represents the wildcard version of the /openconfig-simple/parent/child/state/three YANG schema element.
type OpenconfigSimple_Parent_Child_State_ThreePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "three"
//	Path from root:       "/parent/child/state/three"
func (n *OpenconfigSimple_Parent_Child_State_ThreePath) Query() ygnmi.ConfigQuery[oc.E_Simple_Parent_Child_Config_Three] {
	return ygnmi.NewConfigQuery[oc.E_Simple_Parent_Child_Config_Three](
		"OpenconfigSimple_Parent_Child_State",
		false,
		true,
		false,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"three"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_Simple_Parent_Child_Config_Three, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_State).Three
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "three"
//	Path from root:       "/parent/child/state/three"
func (n *OpenconfigSimple_Parent_Child_State_ThreePathAny) Query() ygnmi.WildcardQuery[oc.E_Simple_Parent_Child_Config_Three] {
	return ygnmi.NewWildcardQuery[oc.E_Simple_Parent_Child_Config_Three](
		"OpenconfigSimple_Parent_Child_State",
		false,
		true,
		false,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"three"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_Simple_Parent_Child_Config_Three, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_State).Three
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}

// OpenconfigSimple_Parent_Child_State_TwoPath represents the /openconfig-simple/parent/child/state/two YANG schema element.
type OpenconfigSimple_Parent_Child_State_TwoPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// OpenconfigSimple_Parent_Child_State_TwoPathAny represents the wildcard version of the /openconfig-simple/parent/child/state/two YANG schema element.
type OpenconfigSimple_Parent_Child_State_TwoPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "two"
//	Path from root:       "/parent/child/state/two"
func (n *OpenconfigSimple_Parent_Child_State_TwoPath) Query() ygnmi.ConfigQuery[string] {
	return ygnmi.NewConfigQuery[string](
		"OpenconfigSimple_Parent_Child_State",
		false,
		true,
		true,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"two"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_State).Two
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "two"
//	Path from root:       "/parent/child/state/two"
func (n *OpenconfigSimple_Parent_Child_State_TwoPathAny) Query() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"OpenconfigSimple_Parent_Child_State",
		false,
		true,
		true,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"two"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.OpenconfigSimple_Parent_Child_State).Two
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_Parent_Child_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}

// OpenconfigSimple_Parent_Child_StatePath represents the /openconfig-simple/parent/child/state YANG schema element.
type OpenconfigSimple_Parent_Child_StatePath struct {
	*ygnmi.NodePath
}

// OpenconfigSimple_Parent_Child_StatePathAny represents the wildcard version of the /openconfig-simple/parent/child/state YANG schema element.
type OpenconfigSimple_Parent_Child_StatePathAny struct {
	*ygnmi.NodePath
}

// Five (leaf):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "five"
//	Path from root:       "/parent/child/state/five"
func (n *OpenconfigSimple_Parent_Child_StatePath) Five() *OpenconfigSimple_Parent_Child_State_FivePath {
	return &OpenconfigSimple_Parent_Child_State_FivePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"five"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Five (leaf):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "five"
//	Path from root:       "/parent/child/state/five"
func (n *OpenconfigSimple_Parent_Child_StatePathAny) Five() *OpenconfigSimple_Parent_Child_State_FivePathAny {
	return &OpenconfigSimple_Parent_Child_State_FivePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"five"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Four (leaf):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "four"
//	Path from root:       "/parent/child/state/four"
func (n *OpenconfigSimple_Parent_Child_StatePath) Four() *OpenconfigSimple_Parent_Child_State_FourPath {
	return &OpenconfigSimple_Parent_Child_State_FourPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"four"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Four (leaf):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "four"
//	Path from root:       "/parent/child/state/four"
func (n *OpenconfigSimple_Parent_Child_StatePathAny) Four() *OpenconfigSimple_Parent_Child_State_FourPathAny {
	return &OpenconfigSimple_Parent_Child_State_FourPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"four"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// One (leaf):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "one"
//	Path from root:       "/parent/child/state/one"
func (n *OpenconfigSimple_Parent_Child_StatePath) One() *OpenconfigSimple_Parent_Child_State_OnePath {
	return &OpenconfigSimple_Parent_Child_State_OnePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"one"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// One (leaf):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "one"
//	Path from root:       "/parent/child/state/one"
func (n *OpenconfigSimple_Parent_Child_StatePathAny) One() *OpenconfigSimple_Parent_Child_State_OnePathAny {
	return &OpenconfigSimple_Parent_Child_State_OnePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"one"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Six (leaf-list):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "six"
//	Path from root:       "/parent/child/state/six"
func (n *OpenconfigSimple_Parent_Child_StatePath) Six() *OpenconfigSimple_Parent_Child_State_SixPath {
	return &OpenconfigSimple_Parent_Child_State_SixPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"six"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Six (leaf-list):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "six"
//	Path from root:       "/parent/child/state/six"
func (n *OpenconfigSimple_Parent_Child_StatePathAny) Six() *OpenconfigSimple_Parent_Child_State_SixPathAny {
	return &OpenconfigSimple_Parent_Child_State_SixPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"six"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Three (leaf):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "three"
//	Path from root:       "/parent/child/state/three"
func (n *OpenconfigSimple_Parent_Child_StatePath) Three() *OpenconfigSimple_Parent_Child_State_ThreePath {
	return &OpenconfigSimple_Parent_Child_State_ThreePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"three"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Three (leaf):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "three"
//	Path from root:       "/parent/child/state/three"
func (n *OpenconfigSimple_Parent_Child_StatePathAny) Three() *OpenconfigSimple_Parent_Child_State_ThreePathAny {
	return &OpenconfigSimple_Parent_Child_State_ThreePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"three"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Two (leaf):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "two"
//	Path from root:       "/parent/child/state/two"
func (n *OpenconfigSimple_Parent_Child_StatePath) Two() *OpenconfigSimple_Parent_Child_State_TwoPath {
	return &OpenconfigSimple_Parent_Child_State_TwoPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"two"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Two (leaf):
//
//	Defining module:      "openconfig-simple"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "two"
//	Path from root:       "/parent/child/state/two"
func (n *OpenconfigSimple_Parent_Child_StatePathAny) Two() *OpenconfigSimple_Parent_Child_State_TwoPathAny {
	return &OpenconfigSimple_Parent_Child_State_TwoPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"two"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Query returns a Query that can be used in gNMI operations.
func (n *OpenconfigSimple_Parent_Child_StatePath) Query() ygnmi.ConfigQuery[*oc.OpenconfigSimple_Parent_Child_State] {
	return ygnmi.NewConfigQuery[*oc.OpenconfigSimple_Parent_Child_State](
		"OpenconfigSimple_Parent_Child_State",
		false,
		false,
		false,
		false,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
func (n *OpenconfigSimple_Parent_Child_StatePathAny) Query() ygnmi.WildcardQuery[*oc.OpenconfigSimple_Parent_Child_State] {
	return ygnmi.NewWildcardQuery[*oc.OpenconfigSimple_Parent_Child_State](
		"OpenconfigSimple_Parent_Child_State",
		false,
		false,
		false,
		false,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}

// OpenconfigSimple_RemoteContainerPath represents the /openconfig-simple/remote-container YANG schema element.
type OpenconfigSimple_RemoteContainerPath struct {
	*ygnmi.NodePath
}

// OpenconfigSimple_RemoteContainerPathAny represents the wildcard version of the /openconfig-simple/remote-container YANG schema element.
type OpenconfigSimple_RemoteContainerPathAny struct {
	*ygnmi.NodePath
}

// Config (container):
//
//	Defining module:      "openconfig-remote"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "config"
//	Path from root:       "/remote-container/config"
func (n *OpenconfigSimple_RemoteContainerPath) Config() *OpenconfigSimple_RemoteContainer_ConfigPath {
	return &OpenconfigSimple_RemoteContainer_ConfigPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"config"},
			map[string]interface{}{},
			n,
		),
	}
}

// Config (container):
//
//	Defining module:      "openconfig-remote"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "config"
//	Path from root:       "/remote-container/config"
func (n *OpenconfigSimple_RemoteContainerPathAny) Config() *OpenconfigSimple_RemoteContainer_ConfigPathAny {
	return &OpenconfigSimple_RemoteContainer_ConfigPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"config"},
			map[string]interface{}{},
			n,
		),
	}
}

// State (container):
//
//	Defining module:      "openconfig-remote"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "state"
//	Path from root:       "/remote-container/state"
func (n *OpenconfigSimple_RemoteContainerPath) State() *OpenconfigSimple_RemoteContainer_StatePath {
	return &OpenconfigSimple_RemoteContainer_StatePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state"},
			map[string]interface{}{},
			n,
		),
	}
}

// State (container):
//
//	Defining module:      "openconfig-remote"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "state"
//	Path from root:       "/remote-container/state"
func (n *OpenconfigSimple_RemoteContainerPathAny) State() *OpenconfigSimple_RemoteContainer_StatePathAny {
	return &OpenconfigSimple_RemoteContainer_StatePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state"},
			map[string]interface{}{},
			n,
		),
	}
}

// Query returns a Query that can be used in gNMI operations.
func (n *OpenconfigSimple_RemoteContainerPath) Query() ygnmi.ConfigQuery[*oc.OpenconfigSimple_RemoteContainer] {
	return ygnmi.NewConfigQuery[*oc.OpenconfigSimple_RemoteContainer](
		"OpenconfigSimple_RemoteContainer",
		false,
		false,
		false,
		false,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
func (n *OpenconfigSimple_RemoteContainerPathAny) Query() ygnmi.WildcardQuery[*oc.OpenconfigSimple_RemoteContainer] {
	return ygnmi.NewWildcardQuery[*oc.OpenconfigSimple_RemoteContainer](
		"OpenconfigSimple_RemoteContainer",
		false,
		false,
		false,
		false,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}

// OpenconfigSimple_RemoteContainer_Config_ALeafPath represents the /openconfig-simple/remote-container/config/a-leaf YANG schema element.
type OpenconfigSimple_RemoteContainer_Config_ALeafPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// OpenconfigSimple_RemoteContainer_Config_ALeafPathAny represents the wildcard version of the /openconfig-simple/remote-container/config/a-leaf YANG schema element.
type OpenconfigSimple_RemoteContainer_Config_ALeafPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-remote"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "a-leaf"
//	Path from root:       "/remote-container/config/a-leaf"
func (n *OpenconfigSimple_RemoteContainer_Config_ALeafPath) Query() ygnmi.ConfigQuery[string] {
	return ygnmi.NewConfigQuery[string](
		"OpenconfigSimple_RemoteContainer_Config",
		false,
		true,
		true,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"a-leaf"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.OpenconfigSimple_RemoteContainer_Config).ALeaf
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_RemoteContainer_Config) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-remote"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "a-leaf"
//	Path from root:       "/remote-container/config/a-leaf"
func (n *OpenconfigSimple_RemoteContainer_Config_ALeafPathAny) Query() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"OpenconfigSimple_RemoteContainer_Config",
		false,
		true,
		true,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"a-leaf"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.OpenconfigSimple_RemoteContainer_Config).ALeaf
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_RemoteContainer_Config) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}

// OpenconfigSimple_RemoteContainer_ConfigPath represents the /openconfig-simple/remote-container/config YANG schema element.
type OpenconfigSimple_RemoteContainer_ConfigPath struct {
	*ygnmi.NodePath
}

// OpenconfigSimple_RemoteContainer_ConfigPathAny represents the wildcard version of the /openconfig-simple/remote-container/config YANG schema element.
type OpenconfigSimple_RemoteContainer_ConfigPathAny struct {
	*ygnmi.NodePath
}

// ALeaf (leaf):
//
//	Defining module:      "openconfig-remote"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "a-leaf"
//	Path from root:       "/remote-container/config/a-leaf"
func (n *OpenconfigSimple_RemoteContainer_ConfigPath) ALeaf() *OpenconfigSimple_RemoteContainer_Config_ALeafPath {
	return &OpenconfigSimple_RemoteContainer_Config_ALeafPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"a-leaf"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// ALeaf (leaf):
//
//	Defining module:      "openconfig-remote"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "a-leaf"
//	Path from root:       "/remote-container/config/a-leaf"
func (n *OpenconfigSimple_RemoteContainer_ConfigPathAny) ALeaf() *OpenconfigSimple_RemoteContainer_Config_ALeafPathAny {
	return &OpenconfigSimple_RemoteContainer_Config_ALeafPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"a-leaf"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Query returns a Query that can be used in gNMI operations.
func (n *OpenconfigSimple_RemoteContainer_ConfigPath) Query() ygnmi.ConfigQuery[*oc.OpenconfigSimple_RemoteContainer_Config] {
	return ygnmi.NewConfigQuery[*oc.OpenconfigSimple_RemoteContainer_Config](
		"OpenconfigSimple_RemoteContainer_Config",
		false,
		false,
		false,
		false,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
func (n *OpenconfigSimple_RemoteContainer_ConfigPathAny) Query() ygnmi.WildcardQuery[*oc.OpenconfigSimple_RemoteContainer_Config] {
	return ygnmi.NewWildcardQuery[*oc.OpenconfigSimple_RemoteContainer_Config](
		"OpenconfigSimple_RemoteContainer_Config",
		false,
		false,
		false,
		false,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}

// OpenconfigSimple_RemoteContainer_State_ALeafPath represents the /openconfig-simple/remote-container/state/a-leaf YANG schema element.
type OpenconfigSimple_RemoteContainer_State_ALeafPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// OpenconfigSimple_RemoteContainer_State_ALeafPathAny represents the wildcard version of the /openconfig-simple/remote-container/state/a-leaf YANG schema element.
type OpenconfigSimple_RemoteContainer_State_ALeafPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-remote"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "a-leaf"
//	Path from root:       "/remote-container/state/a-leaf"
func (n *OpenconfigSimple_RemoteContainer_State_ALeafPath) Query() ygnmi.ConfigQuery[string] {
	return ygnmi.NewConfigQuery[string](
		"OpenconfigSimple_RemoteContainer_State",
		false,
		true,
		true,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"a-leaf"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.OpenconfigSimple_RemoteContainer_State).ALeaf
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_RemoteContainer_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-remote"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "a-leaf"
//	Path from root:       "/remote-container/state/a-leaf"
func (n *OpenconfigSimple_RemoteContainer_State_ALeafPathAny) Query() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"OpenconfigSimple_RemoteContainer_State",
		false,
		true,
		true,
		false,
		false,
		ygnmi.NewNodePath(
			[]string{"a-leaf"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.OpenconfigSimple_RemoteContainer_State).ALeaf
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigSimple_RemoteContainer_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}

// OpenconfigSimple_RemoteContainer_StatePath represents the /openconfig-simple/remote-container/state YANG schema element.
type OpenconfigSimple_RemoteContainer_StatePath struct {
	*ygnmi.NodePath
}

// OpenconfigSimple_RemoteContainer_StatePathAny represents the wildcard version of the /openconfig-simple/remote-container/state YANG schema element.
type OpenconfigSimple_RemoteContainer_StatePathAny struct {
	*ygnmi.NodePath
}

// ALeaf (leaf):
//
//	Defining module:      "openconfig-remote"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "a-leaf"
//	Path from root:       "/remote-container/state/a-leaf"
func (n *OpenconfigSimple_RemoteContainer_StatePath) ALeaf() *OpenconfigSimple_RemoteContainer_State_ALeafPath {
	return &OpenconfigSimple_RemoteContainer_State_ALeafPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"a-leaf"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// ALeaf (leaf):
//
//	Defining module:      "openconfig-remote"
//	Instantiating module: "openconfig-simple"
//	Path from parent:     "a-leaf"
//	Path from root:       "/remote-container/state/a-leaf"
func (n *OpenconfigSimple_RemoteContainer_StatePathAny) ALeaf() *OpenconfigSimple_RemoteContainer_State_ALeafPathAny {
	return &OpenconfigSimple_RemoteContainer_State_ALeafPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"a-leaf"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
}

// Query returns a Query that can be used in gNMI operations.
func (n *OpenconfigSimple_RemoteContainer_StatePath) Query() ygnmi.ConfigQuery[*oc.OpenconfigSimple_RemoteContainer_State] {
	return ygnmi.NewConfigQuery[*oc.OpenconfigSimple_RemoteContainer_State](
		"OpenconfigSimple_RemoteContainer_State",
		false,
		false,
		false,
		false,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Query returns a Query that can be used in gNMI operations.
func (n *OpenconfigSimple_RemoteContainer_StatePathAny) Query() ygnmi.WildcardQuery[*oc.OpenconfigSimple_RemoteContainer_State] {
	return ygnmi.NewWildcardQuery[*oc.OpenconfigSimple_RemoteContainer_State](
		"OpenconfigSimple_RemoteContainer_State",
		false,
		false,
		false,
		false,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
	)
}
