// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
Package unione is a generated package which contains definitions
of structs which generate gNMI paths for a YANG schema.

This package was generated by ygnmi version: (devel): (ygot: v0.34.0)
using the following YANG input files:
  - ../../pathgen/testdata/yang/openconfig-simple.yang
  - ../../pathgen/testdata/yang/openconfig-withlistval.yang
  - ../../pathgen/testdata/yang/openconfig-nested.yang
  - ../../pathgen/testdata/yang/openconfig-unione.yang

Imported modules were sourced from:
*/
package unione

import (
	"reflect"

	oc "github.com/openconfig/ygnmi/internal/uexampleoc"
	"github.com/openconfig/ygnmi/ygnmi"
	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/ygot/ytypes"
)

// OpenconfigUnione_DupEnumPath represents the /openconfig-unione/dup-enum YANG schema element.
type OpenconfigUnione_DupEnumPath struct {
	*ygnmi.NodePath
	ygnmi.ConfigQuery[*oc.OpenconfigUnione_DupEnum]
}

// OpenconfigUnione_DupEnumPathAny represents the wildcard version of the /openconfig-unione/dup-enum YANG schema element.
type OpenconfigUnione_DupEnumPathAny struct {
	*ygnmi.NodePath
	ygnmi.WildcardQuery[*oc.OpenconfigUnione_DupEnum]
}

// PathOrigin returns the name of the origin for the path object.
func (n *OpenconfigUnione_DupEnumPath) PathOriginName() string {
	return "openconfig"
}

// State (container):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "state"
//	Path from root:       "/dup-enum/state"
func (n *OpenconfigUnione_DupEnumPath) State() *OpenconfigUnione_DupEnum_StatePath {
	ps := &OpenconfigUnione_DupEnum_StatePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state"},
			map[string]interface{}{},
			n,
		),
	}
	ps.ConfigQuery = ygnmi.NewConfigQuery[*oc.OpenconfigUnione_DupEnum_State](
		"OpenconfigUnione_DupEnum_State",
		true,
		false,
		false,
		false,
		false,
		false,
		ps,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// State (container):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "state"
//	Path from root:       "/dup-enum/state"
func (n *OpenconfigUnione_DupEnumPathAny) State() *OpenconfigUnione_DupEnum_StatePathAny {
	ps := &OpenconfigUnione_DupEnum_StatePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state"},
			map[string]interface{}{},
			n,
		),
	}
	ps.WildcardQuery = ygnmi.NewWildcardQuery[*oc.OpenconfigUnione_DupEnum_State](
		"OpenconfigUnione_DupEnum_State",
		true,
		false,
		false,
		false,
		false,
		false,
		ps,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

func binarySliceToFloatSlice(in []oc.Binary) []float32 {
	converted := make([]float32, 0, len(in))
	for _, binary := range in {
		converted = append(converted, ygot.BinaryToFloat32(binary))
	}
	return converted
}

// OpenconfigUnione_DupEnum_State_APath represents the /openconfig-unione/dup-enum/state/A YANG schema element.
type OpenconfigUnione_DupEnum_State_APath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.ConfigQuery[oc.E_Unione_DupEnum_State_A]
}

// OpenconfigUnione_DupEnum_State_APathAny represents the wildcard version of the /openconfig-unione/dup-enum/state/A YANG schema element.
type OpenconfigUnione_DupEnum_State_APathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.WildcardQuery[oc.E_Unione_DupEnum_State_A]
}

// PathOrigin returns the name of the origin for the path object.
func (n *OpenconfigUnione_DupEnum_State_APath) PathOriginName() string {
	return ""
}

// OpenconfigUnione_DupEnum_State_BPath represents the /openconfig-unione/dup-enum/state/B YANG schema element.
type OpenconfigUnione_DupEnum_State_BPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.ConfigQuery[oc.E_Unione_DupEnum_State_B]
}

// OpenconfigUnione_DupEnum_State_BPathAny represents the wildcard version of the /openconfig-unione/dup-enum/state/B YANG schema element.
type OpenconfigUnione_DupEnum_State_BPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.WildcardQuery[oc.E_Unione_DupEnum_State_B]
}

// PathOrigin returns the name of the origin for the path object.
func (n *OpenconfigUnione_DupEnum_State_BPath) PathOriginName() string {
	return ""
}

// OpenconfigUnione_DupEnum_StatePath represents the /openconfig-unione/dup-enum/state YANG schema element.
type OpenconfigUnione_DupEnum_StatePath struct {
	*ygnmi.NodePath
	ygnmi.ConfigQuery[*oc.OpenconfigUnione_DupEnum_State]
}

// OpenconfigUnione_DupEnum_StatePathAny represents the wildcard version of the /openconfig-unione/dup-enum/state YANG schema element.
type OpenconfigUnione_DupEnum_StatePathAny struct {
	*ygnmi.NodePath
	ygnmi.WildcardQuery[*oc.OpenconfigUnione_DupEnum_State]
}

// PathOrigin returns the name of the origin for the path object.
func (n *OpenconfigUnione_DupEnum_StatePath) PathOriginName() string {
	return "openconfig"
}

// A (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "A"
//	Path from root:       "/dup-enum/state/A"
func (n *OpenconfigUnione_DupEnum_StatePath) A() *OpenconfigUnione_DupEnum_State_APath {
	ps := &OpenconfigUnione_DupEnum_State_APath{
		NodePath: ygnmi.NewNodePath(
			[]string{"A"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.ConfigQuery = ygnmi.NewConfigQuery[oc.E_Unione_DupEnum_State_A](
		"OpenconfigUnione_DupEnum_State",
		true,
		false,
		true,
		false,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (oc.E_Unione_DupEnum_State_A, bool) {
			ret := gs.(*oc.OpenconfigUnione_DupEnum_State).A
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_DupEnum_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// A (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "A"
//	Path from root:       "/dup-enum/state/A"
func (n *OpenconfigUnione_DupEnum_StatePathAny) A() *OpenconfigUnione_DupEnum_State_APathAny {
	ps := &OpenconfigUnione_DupEnum_State_APathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"A"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.WildcardQuery = ygnmi.NewWildcardQuery[oc.E_Unione_DupEnum_State_A](
		"OpenconfigUnione_DupEnum_State",
		true,
		false,
		true,
		false,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (oc.E_Unione_DupEnum_State_A, bool) {
			ret := gs.(*oc.OpenconfigUnione_DupEnum_State).A
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_DupEnum_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// B (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "B"
//	Path from root:       "/dup-enum/state/B"
func (n *OpenconfigUnione_DupEnum_StatePath) B() *OpenconfigUnione_DupEnum_State_BPath {
	ps := &OpenconfigUnione_DupEnum_State_BPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"B"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.ConfigQuery = ygnmi.NewConfigQuery[oc.E_Unione_DupEnum_State_B](
		"OpenconfigUnione_DupEnum_State",
		true,
		false,
		true,
		false,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (oc.E_Unione_DupEnum_State_B, bool) {
			ret := gs.(*oc.OpenconfigUnione_DupEnum_State).B
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_DupEnum_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// B (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "B"
//	Path from root:       "/dup-enum/state/B"
func (n *OpenconfigUnione_DupEnum_StatePathAny) B() *OpenconfigUnione_DupEnum_State_BPathAny {
	ps := &OpenconfigUnione_DupEnum_State_BPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"B"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.WildcardQuery = ygnmi.NewWildcardQuery[oc.E_Unione_DupEnum_State_B](
		"OpenconfigUnione_DupEnum_State",
		true,
		false,
		true,
		false,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (oc.E_Unione_DupEnum_State_B, bool) {
			ret := gs.(*oc.OpenconfigUnione_DupEnum_State).B
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_DupEnum_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// OpenconfigUnione_PlatformPath represents the /openconfig-unione/platform YANG schema element.
type OpenconfigUnione_PlatformPath struct {
	*ygnmi.NodePath
	ygnmi.ConfigQuery[*oc.OpenconfigUnione_Platform]
}

// OpenconfigUnione_PlatformPathAny represents the wildcard version of the /openconfig-unione/platform YANG schema element.
type OpenconfigUnione_PlatformPathAny struct {
	*ygnmi.NodePath
	ygnmi.WildcardQuery[*oc.OpenconfigUnione_Platform]
}

// PathOrigin returns the name of the origin for the path object.
func (n *OpenconfigUnione_PlatformPath) PathOriginName() string {
	return "openconfig"
}

// ComponentAny (list):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "component"
//	Path from root:       "/platform/component"
func (n *OpenconfigUnione_PlatformPath) ComponentAny() *OpenconfigUnione_Platform_ComponentPathAny {
	ps := &OpenconfigUnione_Platform_ComponentPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"component"},
			map[string]interface{}{"name": "*"},
			n,
		),
	}
	ps.WildcardQuery = ygnmi.NewWildcardQuery[*oc.OpenconfigUnione_Platform_Component](
		"OpenconfigUnione_Platform_Component",
		true,
		false,
		false,
		false,
		false,
		false,
		ps,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// ComponentAny (list):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "component"
//	Path from root:       "/platform/component"
func (n *OpenconfigUnione_PlatformPathAny) ComponentAny() *OpenconfigUnione_Platform_ComponentPathAny {
	ps := &OpenconfigUnione_Platform_ComponentPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"component"},
			map[string]interface{}{"name": "*"},
			n,
		),
	}
	ps.WildcardQuery = ygnmi.NewWildcardQuery[*oc.OpenconfigUnione_Platform_Component](
		"OpenconfigUnione_Platform_Component",
		true,
		false,
		false,
		false,
		false,
		false,
		ps,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// Component (list):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "component"
//	Path from root:       "/platform/component"
//
//	Name: string
func (n *OpenconfigUnione_PlatformPath) Component(Name string) *OpenconfigUnione_Platform_ComponentPath {
	ps := &OpenconfigUnione_Platform_ComponentPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"component"},
			map[string]interface{}{"name": Name},
			n,
		),
	}
	ps.ConfigQuery = ygnmi.NewConfigQuery[*oc.OpenconfigUnione_Platform_Component](
		"OpenconfigUnione_Platform_Component",
		true,
		false,
		false,
		false,
		false,
		false,
		ps,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// Component (list):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "component"
//	Path from root:       "/platform/component"
//
//	Name: string
func (n *OpenconfigUnione_PlatformPathAny) Component(Name string) *OpenconfigUnione_Platform_ComponentPathAny {
	ps := &OpenconfigUnione_Platform_ComponentPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"component"},
			map[string]interface{}{"name": Name},
			n,
		),
	}
	ps.WildcardQuery = ygnmi.NewWildcardQuery[*oc.OpenconfigUnione_Platform_Component](
		"OpenconfigUnione_Platform_Component",
		true,
		false,
		false,
		false,
		false,
		false,
		ps,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// ComponentMap (list):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "component"
//	Path from root:       "/platform/component"
func (n *OpenconfigUnione_PlatformPath) ComponentMap() *OpenconfigUnione_Platform_ComponentPathMap {
	ps := &OpenconfigUnione_Platform_ComponentPathMap{
		NodePath: ygnmi.NewNodePath(
			[]string{"component"},
			map[string]interface{}{},
			n,
		),
	}
	ps.ConfigQuery = ygnmi.NewConfigQuery[map[string]*oc.OpenconfigUnione_Platform_Component](
		"OpenconfigUnione_Platform",
		true,
		false,
		false,
		false,
		false,
		true,
		ps,
		func(gs ygot.ValidatedGoStruct) (map[string]*oc.OpenconfigUnione_Platform_Component, bool) {
			ret := gs.(*oc.OpenconfigUnione_Platform).Component
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_Platform) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// ComponentMap (list):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "component"
//	Path from root:       "/platform/component"
func (n *OpenconfigUnione_PlatformPathAny) ComponentMap() *OpenconfigUnione_Platform_ComponentPathMapAny {
	ps := &OpenconfigUnione_Platform_ComponentPathMapAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"component"},
			map[string]interface{}{},
			n,
		),
	}
	ps.WildcardQuery = ygnmi.NewWildcardQuery[map[string]*oc.OpenconfigUnione_Platform_Component](
		"OpenconfigUnione_Platform",
		true,
		false,
		false,
		false,
		false,
		true,
		ps,
		func(gs ygot.ValidatedGoStruct) (map[string]*oc.OpenconfigUnione_Platform_Component, bool) {
			ret := gs.(*oc.OpenconfigUnione_Platform).Component
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_Platform) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// OpenconfigUnione_Platform_Component_NamePath represents the /openconfig-unione/platform/component/name YANG schema element.
type OpenconfigUnione_Platform_Component_NamePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.ConfigQuery[string]
}

// OpenconfigUnione_Platform_Component_NamePathAny represents the wildcard version of the /openconfig-unione/platform/component/name YANG schema element.
type OpenconfigUnione_Platform_Component_NamePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.WildcardQuery[string]
}

// PathOrigin returns the name of the origin for the path object.
func (n *OpenconfigUnione_Platform_Component_NamePath) PathOriginName() string {
	return ""
}

// OpenconfigUnione_Platform_ComponentPath represents the /openconfig-unione/platform/component YANG schema element.
type OpenconfigUnione_Platform_ComponentPath struct {
	*ygnmi.NodePath
	ygnmi.ConfigQuery[*oc.OpenconfigUnione_Platform_Component]
}

// OpenconfigUnione_Platform_ComponentPathAny represents the wildcard version of the /openconfig-unione/platform/component YANG schema element.
type OpenconfigUnione_Platform_ComponentPathAny struct {
	*ygnmi.NodePath
	ygnmi.WildcardQuery[*oc.OpenconfigUnione_Platform_Component]
}

// PathOrigin returns the name of the origin for the path object.
func (n *OpenconfigUnione_Platform_ComponentPath) PathOriginName() string {
	return "openconfig"
}

// OpenconfigUnione_Platform_ComponentPathMap represents the /openconfig-unione/platform/component YANG schema element.
type OpenconfigUnione_Platform_ComponentPathMap struct {
	*ygnmi.NodePath
	ygnmi.ConfigQuery[map[string]*oc.OpenconfigUnione_Platform_Component]
}

// OpenconfigUnione_Platform_ComponentPathMapAny represents the wildcard version of the /openconfig-unione/platform/component YANG schema element.
type OpenconfigUnione_Platform_ComponentPathMapAny struct {
	*ygnmi.NodePath
	ygnmi.WildcardQuery[map[string]*oc.OpenconfigUnione_Platform_Component]
}

// PathOrigin returns the name of the origin for the path object.
func (n *OpenconfigUnione_Platform_ComponentPathMap) PathOriginName() string {
	return "openconfig"
}

// Config (container):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "config"
//	Path from root:       "/platform/component/config"
func (n *OpenconfigUnione_Platform_ComponentPath) Config() *OpenconfigUnione_Platform_Component_ConfigPath {
	ps := &OpenconfigUnione_Platform_Component_ConfigPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"config"},
			map[string]interface{}{},
			n,
		),
	}
	ps.ConfigQuery = ygnmi.NewConfigQuery[*oc.OpenconfigUnione_Platform_Component_Config](
		"OpenconfigUnione_Platform_Component_Config",
		true,
		false,
		false,
		false,
		false,
		false,
		ps,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// Config (container):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "config"
//	Path from root:       "/platform/component/config"
func (n *OpenconfigUnione_Platform_ComponentPathAny) Config() *OpenconfigUnione_Platform_Component_ConfigPathAny {
	ps := &OpenconfigUnione_Platform_Component_ConfigPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"config"},
			map[string]interface{}{},
			n,
		),
	}
	ps.WildcardQuery = ygnmi.NewWildcardQuery[*oc.OpenconfigUnione_Platform_Component_Config](
		"OpenconfigUnione_Platform_Component_Config",
		true,
		false,
		false,
		false,
		false,
		false,
		ps,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// Name (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "name"
//	Path from root:       "/platform/component/name"
func (n *OpenconfigUnione_Platform_ComponentPath) Name() *OpenconfigUnione_Platform_Component_NamePath {
	ps := &OpenconfigUnione_Platform_Component_NamePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"name"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.ConfigQuery = ygnmi.NewConfigQuery[string](
		"OpenconfigUnione_Platform_Component",
		true,
		false,
		true,
		true,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.OpenconfigUnione_Platform_Component).Name
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_Platform_Component) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// Name (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "name"
//	Path from root:       "/platform/component/name"
func (n *OpenconfigUnione_Platform_ComponentPathAny) Name() *OpenconfigUnione_Platform_Component_NamePathAny {
	ps := &OpenconfigUnione_Platform_Component_NamePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"name"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.WildcardQuery = ygnmi.NewWildcardQuery[string](
		"OpenconfigUnione_Platform_Component",
		true,
		false,
		true,
		true,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.OpenconfigUnione_Platform_Component).Name
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_Platform_Component) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// State (container):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "state"
//	Path from root:       "/platform/component/state"
func (n *OpenconfigUnione_Platform_ComponentPath) State() *OpenconfigUnione_Platform_Component_StatePath {
	ps := &OpenconfigUnione_Platform_Component_StatePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state"},
			map[string]interface{}{},
			n,
		),
	}
	ps.ConfigQuery = ygnmi.NewConfigQuery[*oc.OpenconfigUnione_Platform_Component_State](
		"OpenconfigUnione_Platform_Component_State",
		true,
		false,
		false,
		false,
		false,
		false,
		ps,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// State (container):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "state"
//	Path from root:       "/platform/component/state"
func (n *OpenconfigUnione_Platform_ComponentPathAny) State() *OpenconfigUnione_Platform_Component_StatePathAny {
	ps := &OpenconfigUnione_Platform_Component_StatePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state"},
			map[string]interface{}{},
			n,
		),
	}
	ps.WildcardQuery = ygnmi.NewWildcardQuery[*oc.OpenconfigUnione_Platform_Component_State](
		"OpenconfigUnione_Platform_Component_State",
		true,
		false,
		false,
		false,
		false,
		false,
		ps,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// OpenconfigUnione_Platform_Component_Config_NamePath represents the /openconfig-unione/platform/component/config/name YANG schema element.
type OpenconfigUnione_Platform_Component_Config_NamePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.ConfigQuery[string]
}

// OpenconfigUnione_Platform_Component_Config_NamePathAny represents the wildcard version of the /openconfig-unione/platform/component/config/name YANG schema element.
type OpenconfigUnione_Platform_Component_Config_NamePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.WildcardQuery[string]
}

// PathOrigin returns the name of the origin for the path object.
func (n *OpenconfigUnione_Platform_Component_Config_NamePath) PathOriginName() string {
	return ""
}

// OpenconfigUnione_Platform_Component_ConfigPath represents the /openconfig-unione/platform/component/config YANG schema element.
type OpenconfigUnione_Platform_Component_ConfigPath struct {
	*ygnmi.NodePath
	ygnmi.ConfigQuery[*oc.OpenconfigUnione_Platform_Component_Config]
}

// OpenconfigUnione_Platform_Component_ConfigPathAny represents the wildcard version of the /openconfig-unione/platform/component/config YANG schema element.
type OpenconfigUnione_Platform_Component_ConfigPathAny struct {
	*ygnmi.NodePath
	ygnmi.WildcardQuery[*oc.OpenconfigUnione_Platform_Component_Config]
}

// PathOrigin returns the name of the origin for the path object.
func (n *OpenconfigUnione_Platform_Component_ConfigPath) PathOriginName() string {
	return "openconfig"
}

// Name (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "name"
//	Path from root:       "/platform/component/config/name"
func (n *OpenconfigUnione_Platform_Component_ConfigPath) Name() *OpenconfigUnione_Platform_Component_Config_NamePath {
	ps := &OpenconfigUnione_Platform_Component_Config_NamePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"name"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.ConfigQuery = ygnmi.NewConfigQuery[string](
		"OpenconfigUnione_Platform_Component_Config",
		true,
		false,
		true,
		true,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.OpenconfigUnione_Platform_Component_Config).Name
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_Platform_Component_Config) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// Name (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "name"
//	Path from root:       "/platform/component/config/name"
func (n *OpenconfigUnione_Platform_Component_ConfigPathAny) Name() *OpenconfigUnione_Platform_Component_Config_NamePathAny {
	ps := &OpenconfigUnione_Platform_Component_Config_NamePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"name"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.WildcardQuery = ygnmi.NewWildcardQuery[string](
		"OpenconfigUnione_Platform_Component_Config",
		true,
		false,
		true,
		true,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.OpenconfigUnione_Platform_Component_Config).Name
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_Platform_Component_Config) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// OpenconfigUnione_Platform_Component_State_E1Path represents the /openconfig-unione/platform/component/state/e1 YANG schema element.
type OpenconfigUnione_Platform_Component_State_E1Path struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.ConfigQuery[oc.OpenconfigUnione_Platform_Component_State_E1_Union]
}

// OpenconfigUnione_Platform_Component_State_E1PathAny represents the wildcard version of the /openconfig-unione/platform/component/state/e1 YANG schema element.
type OpenconfigUnione_Platform_Component_State_E1PathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.WildcardQuery[oc.OpenconfigUnione_Platform_Component_State_E1_Union]
}

// PathOrigin returns the name of the origin for the path object.
func (n *OpenconfigUnione_Platform_Component_State_E1Path) PathOriginName() string {
	return ""
}

// OpenconfigUnione_Platform_Component_State_EnumeratedPath represents the /openconfig-unione/platform/component/state/enumerated YANG schema element.
type OpenconfigUnione_Platform_Component_State_EnumeratedPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.ConfigQuery[oc.OpenconfigUnione_Platform_Component_State_Enumerated_Union]
}

// OpenconfigUnione_Platform_Component_State_EnumeratedPathAny represents the wildcard version of the /openconfig-unione/platform/component/state/enumerated YANG schema element.
type OpenconfigUnione_Platform_Component_State_EnumeratedPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.WildcardQuery[oc.OpenconfigUnione_Platform_Component_State_Enumerated_Union]
}

// PathOrigin returns the name of the origin for the path object.
func (n *OpenconfigUnione_Platform_Component_State_EnumeratedPath) PathOriginName() string {
	return ""
}

// OpenconfigUnione_Platform_Component_State_NamePath represents the /openconfig-unione/platform/component/state/name YANG schema element.
type OpenconfigUnione_Platform_Component_State_NamePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.ConfigQuery[string]
}

// OpenconfigUnione_Platform_Component_State_NamePathAny represents the wildcard version of the /openconfig-unione/platform/component/state/name YANG schema element.
type OpenconfigUnione_Platform_Component_State_NamePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.WildcardQuery[string]
}

// PathOrigin returns the name of the origin for the path object.
func (n *OpenconfigUnione_Platform_Component_State_NamePath) PathOriginName() string {
	return ""
}

// OpenconfigUnione_Platform_Component_State_PowerPath represents the /openconfig-unione/platform/component/state/power YANG schema element.
type OpenconfigUnione_Platform_Component_State_PowerPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.ConfigQuery[oc.OpenconfigUnione_Platform_Component_State_Power_Union]
}

// OpenconfigUnione_Platform_Component_State_PowerPathAny represents the wildcard version of the /openconfig-unione/platform/component/state/power YANG schema element.
type OpenconfigUnione_Platform_Component_State_PowerPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.WildcardQuery[oc.OpenconfigUnione_Platform_Component_State_Power_Union]
}

// PathOrigin returns the name of the origin for the path object.
func (n *OpenconfigUnione_Platform_Component_State_PowerPath) PathOriginName() string {
	return ""
}

// OpenconfigUnione_Platform_Component_State_R1Path represents the /openconfig-unione/platform/component/state/r1 YANG schema element.
type OpenconfigUnione_Platform_Component_State_R1Path struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.ConfigQuery[oc.OpenconfigUnione_Platform_Component_State_E1_Union]
}

// OpenconfigUnione_Platform_Component_State_R1PathAny represents the wildcard version of the /openconfig-unione/platform/component/state/r1 YANG schema element.
type OpenconfigUnione_Platform_Component_State_R1PathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.WildcardQuery[oc.OpenconfigUnione_Platform_Component_State_E1_Union]
}

// PathOrigin returns the name of the origin for the path object.
func (n *OpenconfigUnione_Platform_Component_State_R1Path) PathOriginName() string {
	return ""
}

// OpenconfigUnione_Platform_Component_State_TypePath represents the /openconfig-unione/platform/component/state/type YANG schema element.
type OpenconfigUnione_Platform_Component_State_TypePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.ConfigQuery[oc.OpenconfigUnione_Platform_Component_State_Type_Union]
}

// OpenconfigUnione_Platform_Component_State_TypePathAny represents the wildcard version of the /openconfig-unione/platform/component/state/type YANG schema element.
type OpenconfigUnione_Platform_Component_State_TypePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
	ygnmi.WildcardQuery[oc.OpenconfigUnione_Platform_Component_State_Type_Union]
}

// PathOrigin returns the name of the origin for the path object.
func (n *OpenconfigUnione_Platform_Component_State_TypePath) PathOriginName() string {
	return ""
}

// OpenconfigUnione_Platform_Component_StatePath represents the /openconfig-unione/platform/component/state YANG schema element.
type OpenconfigUnione_Platform_Component_StatePath struct {
	*ygnmi.NodePath
	ygnmi.ConfigQuery[*oc.OpenconfigUnione_Platform_Component_State]
}

// OpenconfigUnione_Platform_Component_StatePathAny represents the wildcard version of the /openconfig-unione/platform/component/state YANG schema element.
type OpenconfigUnione_Platform_Component_StatePathAny struct {
	*ygnmi.NodePath
	ygnmi.WildcardQuery[*oc.OpenconfigUnione_Platform_Component_State]
}

// PathOrigin returns the name of the origin for the path object.
func (n *OpenconfigUnione_Platform_Component_StatePath) PathOriginName() string {
	return "openconfig"
}

// E1 (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "e1"
//	Path from root:       "/platform/component/state/e1"
func (n *OpenconfigUnione_Platform_Component_StatePath) E1() *OpenconfigUnione_Platform_Component_State_E1Path {
	ps := &OpenconfigUnione_Platform_Component_State_E1Path{
		NodePath: ygnmi.NewNodePath(
			[]string{"e1"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.ConfigQuery = ygnmi.NewConfigQuery[oc.OpenconfigUnione_Platform_Component_State_E1_Union](
		"OpenconfigUnione_Platform_Component_State",
		true,
		false,
		true,
		false,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (oc.OpenconfigUnione_Platform_Component_State_E1_Union, bool) {
			ret := gs.(*oc.OpenconfigUnione_Platform_Component_State).E1
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_Platform_Component_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// E1 (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "e1"
//	Path from root:       "/platform/component/state/e1"
func (n *OpenconfigUnione_Platform_Component_StatePathAny) E1() *OpenconfigUnione_Platform_Component_State_E1PathAny {
	ps := &OpenconfigUnione_Platform_Component_State_E1PathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"e1"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.WildcardQuery = ygnmi.NewWildcardQuery[oc.OpenconfigUnione_Platform_Component_State_E1_Union](
		"OpenconfigUnione_Platform_Component_State",
		true,
		false,
		true,
		false,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (oc.OpenconfigUnione_Platform_Component_State_E1_Union, bool) {
			ret := gs.(*oc.OpenconfigUnione_Platform_Component_State).E1
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_Platform_Component_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// Enumerated (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "enumerated"
//	Path from root:       "/platform/component/state/enumerated"
func (n *OpenconfigUnione_Platform_Component_StatePath) Enumerated() *OpenconfigUnione_Platform_Component_State_EnumeratedPath {
	ps := &OpenconfigUnione_Platform_Component_State_EnumeratedPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"enumerated"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.ConfigQuery = ygnmi.NewConfigQuery[oc.OpenconfigUnione_Platform_Component_State_Enumerated_Union](
		"OpenconfigUnione_Platform_Component_State",
		true,
		false,
		true,
		false,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (oc.OpenconfigUnione_Platform_Component_State_Enumerated_Union, bool) {
			ret := gs.(*oc.OpenconfigUnione_Platform_Component_State).Enumerated
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_Platform_Component_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// Enumerated (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "enumerated"
//	Path from root:       "/platform/component/state/enumerated"
func (n *OpenconfigUnione_Platform_Component_StatePathAny) Enumerated() *OpenconfigUnione_Platform_Component_State_EnumeratedPathAny {
	ps := &OpenconfigUnione_Platform_Component_State_EnumeratedPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"enumerated"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.WildcardQuery = ygnmi.NewWildcardQuery[oc.OpenconfigUnione_Platform_Component_State_Enumerated_Union](
		"OpenconfigUnione_Platform_Component_State",
		true,
		false,
		true,
		false,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (oc.OpenconfigUnione_Platform_Component_State_Enumerated_Union, bool) {
			ret := gs.(*oc.OpenconfigUnione_Platform_Component_State).Enumerated
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_Platform_Component_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// Name (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "name"
//	Path from root:       "/platform/component/state/name"
func (n *OpenconfigUnione_Platform_Component_StatePath) Name() *OpenconfigUnione_Platform_Component_State_NamePath {
	ps := &OpenconfigUnione_Platform_Component_State_NamePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"name"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.ConfigQuery = ygnmi.NewConfigQuery[string](
		"OpenconfigUnione_Platform_Component_State",
		true,
		false,
		true,
		true,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.OpenconfigUnione_Platform_Component_State).Name
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_Platform_Component_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// Name (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "name"
//	Path from root:       "/platform/component/state/name"
func (n *OpenconfigUnione_Platform_Component_StatePathAny) Name() *OpenconfigUnione_Platform_Component_State_NamePathAny {
	ps := &OpenconfigUnione_Platform_Component_State_NamePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"name"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.WildcardQuery = ygnmi.NewWildcardQuery[string](
		"OpenconfigUnione_Platform_Component_State",
		true,
		false,
		true,
		true,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.OpenconfigUnione_Platform_Component_State).Name
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_Platform_Component_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// Power (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "power"
//	Path from root:       "/platform/component/state/power"
func (n *OpenconfigUnione_Platform_Component_StatePath) Power() *OpenconfigUnione_Platform_Component_State_PowerPath {
	ps := &OpenconfigUnione_Platform_Component_State_PowerPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"power"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.ConfigQuery = ygnmi.NewConfigQuery[oc.OpenconfigUnione_Platform_Component_State_Power_Union](
		"OpenconfigUnione_Platform_Component_State",
		true,
		false,
		true,
		false,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (oc.OpenconfigUnione_Platform_Component_State_Power_Union, bool) {
			ret := gs.(*oc.OpenconfigUnione_Platform_Component_State).Power
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_Platform_Component_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// Power (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "power"
//	Path from root:       "/platform/component/state/power"
func (n *OpenconfigUnione_Platform_Component_StatePathAny) Power() *OpenconfigUnione_Platform_Component_State_PowerPathAny {
	ps := &OpenconfigUnione_Platform_Component_State_PowerPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"power"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.WildcardQuery = ygnmi.NewWildcardQuery[oc.OpenconfigUnione_Platform_Component_State_Power_Union](
		"OpenconfigUnione_Platform_Component_State",
		true,
		false,
		true,
		false,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (oc.OpenconfigUnione_Platform_Component_State_Power_Union, bool) {
			ret := gs.(*oc.OpenconfigUnione_Platform_Component_State).Power
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_Platform_Component_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// R1 (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "r1"
//	Path from root:       "/platform/component/state/r1"
func (n *OpenconfigUnione_Platform_Component_StatePath) R1() *OpenconfigUnione_Platform_Component_State_R1Path {
	ps := &OpenconfigUnione_Platform_Component_State_R1Path{
		NodePath: ygnmi.NewNodePath(
			[]string{"r1"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.ConfigQuery = ygnmi.NewConfigQuery[oc.OpenconfigUnione_Platform_Component_State_E1_Union](
		"OpenconfigUnione_Platform_Component_State",
		true,
		false,
		true,
		false,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (oc.OpenconfigUnione_Platform_Component_State_E1_Union, bool) {
			ret := gs.(*oc.OpenconfigUnione_Platform_Component_State).R1
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_Platform_Component_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// R1 (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "r1"
//	Path from root:       "/platform/component/state/r1"
func (n *OpenconfigUnione_Platform_Component_StatePathAny) R1() *OpenconfigUnione_Platform_Component_State_R1PathAny {
	ps := &OpenconfigUnione_Platform_Component_State_R1PathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"r1"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.WildcardQuery = ygnmi.NewWildcardQuery[oc.OpenconfigUnione_Platform_Component_State_E1_Union](
		"OpenconfigUnione_Platform_Component_State",
		true,
		false,
		true,
		false,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (oc.OpenconfigUnione_Platform_Component_State_E1_Union, bool) {
			ret := gs.(*oc.OpenconfigUnione_Platform_Component_State).R1
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_Platform_Component_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// Type (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "type"
//	Path from root:       "/platform/component/state/type"
func (n *OpenconfigUnione_Platform_Component_StatePath) Type() *OpenconfigUnione_Platform_Component_State_TypePath {
	ps := &OpenconfigUnione_Platform_Component_State_TypePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"type"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.ConfigQuery = ygnmi.NewConfigQuery[oc.OpenconfigUnione_Platform_Component_State_Type_Union](
		"OpenconfigUnione_Platform_Component_State",
		true,
		false,
		true,
		false,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (oc.OpenconfigUnione_Platform_Component_State_Type_Union, bool) {
			ret := gs.(*oc.OpenconfigUnione_Platform_Component_State).Type
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_Platform_Component_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}

// Type (leaf):
//
//	Defining module:      "openconfig-unione"
//	Instantiating module: "openconfig-unione"
//	Path from parent:     "type"
//	Path from root:       "/platform/component/state/type"
func (n *OpenconfigUnione_Platform_Component_StatePathAny) Type() *OpenconfigUnione_Platform_Component_State_TypePathAny {
	ps := &OpenconfigUnione_Platform_Component_State_TypePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"type"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	ps.WildcardQuery = ygnmi.NewWildcardQuery[oc.OpenconfigUnione_Platform_Component_State_Type_Union](
		"OpenconfigUnione_Platform_Component_State",
		true,
		false,
		true,
		false,
		false,
		false,
		ps,
		func(gs ygot.ValidatedGoStruct) (oc.OpenconfigUnione_Platform_Component_State_Type_Union, bool) {
			ret := gs.(*oc.OpenconfigUnione_Platform_Component_State).Type
			return ret, !reflect.ValueOf(ret).IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.OpenconfigUnione_Platform_Component_State) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Device{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)

	return ps
}
